### ISSUE TITLE
Sprint 28 (2018-07-27)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1002]
### Finish database refactor for archival pres copies 
- [ ] rename endpoint (#979)
- [ ] rename pres_copy (possibly postponable) (#980)

### Hook up replication trigger
- [ ] wire up automatic replication (#913, #812, #886)

### C2A
- [ ] for each online pres_copy, does it have all the archival pres_copies it should? (#920)

#### Replicate backlog of druid versions
- [ ] can't determine what needs to be replicated (#907)
