### ISSUE TITLE
Sprint 29 (2018-08-03)

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#1025]
#### C2A
- [ ] for each complete_moab, does it have all the zipped_moab_versions it should and the correct md5? (#920) 

- [x] Fix `create_zip!` deadlocking (#1034)

#### PO2R
- [ ] missing replicated complete_moabs  are put in replication queue (#920)

#### CV
- [x]  CV hookup when checksums_validated=false create or update_version of complete_moab (#990)
- [x] (CV) cron job schedule with whenever  for sending CV requests to queues (#649, #867)

#### Documentation
- [x] Clean DB README schema or delete it (1 day)

#### Replicate backlog of druid versions
- [x] can't determine what needs to be replicated (#907)
- [ ] Have a way to replicate in bulk (#866) (1 week)
- [ ] Pre-delivery checksumming (awaiting ticket number)

#### Documentation
- [ ] DevOps Operations Concerns (#698)  (2 days)
- [ ] Repo Admin Docs (#820) (2 days)
