### ISSUE TITLE
Sprint 30 (2018-08-10)

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#1052]
#### C2A
- [x] for each complete_moab, does it have all the zipped_moab_versions it should and the correct md5? (#973, #994, #998) 

#### PO2R
- [x] missing replicated complete_moabs  are put in replication queue (#900, #901, #920)

#### CV
- [x] (CV) cron job schedule with whenever  for sending CV requests to queues (#649, #867) (This is done but need to check after Sunday 1am to make sure its working correctly. ) 

#### Documentation
- [x] DevOps Operations Concerns (#698)  (2 days)

- [x] Pre-delivery checksumming (#1040)

- [x] implement cache expiry in zip transfers volume (#1032)

#### Replicate backlog of druid versions
- [x] Have a way to replicate in bulk (#866) (1 week)
   - [ ] **ACTION**: Create some rake tasks or documentation to easily do this? Some canned queries

#### Documentation
- [x] Update README (2 days)
- [x] Update db/README (2 days)
- [x] Repo Admin Docs (#820) (2 days)

#### M2C
- [x] move into queues
 #### C2M
- [x] move into queues

**Comment by julianmorley** [comment]
Sample canned query: Select all druid-versions that do not have an archive record on us-west-2, that are less than 10GB in size, limit 1000 results. Feed this to zipmaker.
aka All druid-versions that are not on (specified endpoint), with optional size limit, and optional limit on total druid-versions returned.

**Comment by SaravShah** [comment]
@jermnelson ^
