### ISSUE TITLE
Prepare presentation on Preservation Catalog (knowledge transfer for infra team at large)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1150]
#### TODO

- [x] link to db readme from front page readme
- [x] make sure [db readme](/sul-dlss/preservation_catalog/blob/master/db/README.md) is up to date
  - [x] make sure example queries still work
- [x] make sure [front page readme](/sul-dlss/preservation_catalog/blob/master/README.md) is up to date
- [x] update [queue diagram](https://www.lucidchart.com/documents/edit/d680072f-68e3-4644-91d3-4f20a3fdcd12/0) as needed
  - [x] might already be this way, but if it's not, try to make it so it doesn't need updating when a new endpoint is added
- [x] put queue diagram in repo, with explanation of queue system
- [x] put christina architecture decisions Q&A from slack in wiki page or something -- https://github.com/sul-dlss/preservation_catalog/wiki/Architecture-Review
  - [x] ticket putting it in an ADR, w/ the caveat that it might not actually be worthwhile to do so yet (just an idea if there's time and if we start using ADRs) (#1157)

**Comment by jmartin-sul** [comment]
notes from today's meeting:  https://github.com/sul-dlss/preservation_catalog/wiki/Notes-from-Preservation-Catalog-knowledge-transfer

**Comment by jmartin-sul** [comment]
presentation given, notes saved, checkboxes checked, PR up for review, closing this
