### ISSUE TITLE
[EPIC] Deal with M2C errors on all objects affected by API endpoint issue

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/preservation_catalog#1289]
This is an epic that was identified earlier today in a [meeting](https://docs.google.com/document/d/1FsoFOl9izY6vBkVNbqvaZ6k9L4OQIKcUQI_qUCA90rk/edit) discussing production prescat issues discovered this week. It encompasses the following work:

- [x] #1286 (can start NOW)
- [x] #1287 (can start after current M2C run finishes, possibly as soon as morning of Thursday, 12/19)
- [x] #1288 (can start after #1286 and #1287 are closed)

**Comment by ndushay** [comment]
To conclude: 

- there are 513 complete_moab objects in prescat with "invalid_checksum" 
- the only objects going through preservation-robots that would NOT have been automatically fixed by an M2C run are those with "invalid_checksum" error messages in M2C:  [m2c-invalid-checksum-druids.txt](https://github.com/sul-dlss/preservation_catalog/files/3990365/m2c-invalid-checksum-druids.txt) - 513 of them
- none of the 516 objects (fewer actually - made sure to get some druids before and after the outage)  that ran through preservation-robots during the outage  [prod-druids-alpha.txt](https://github.com/sul-dlss/preservation_catalog/files/3985393/prod-druids-alpha.txt) overlap with the M2C "invalid_checksum" objects

Yes, we still need to address the 513 "invalid_checksum" objects - but that has been a problem, with a stable number, for quite a while now.

tagging @andrewjbtw and @jmartin-sul to let them know;  closing this ticket.
