### ISSUE TITLE
[UBER] preservation PROD storage migration #1

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1465]
assuming the dry run outlined in #1462 completes without issue, we'll do the first round of production storage migration on the same storage roots, on Apr 24, 2020.  the disks to be migrated will be:
* services-disk02: #1502
* services-disk03: #1503
* services-disk04: #1504
* services-disk05: #1505
* services-disk06: #1506
* services-disk07: #1507
* services-disk08: #1508
* services-disk09: #1509
* services-disk10: #1510
* services-disk11: #1511
* services-disk12: #1512
* services-disk17: #1513

here is the same list as a ruby string array, for easier rails console query usage:
```ruby
%w[services-disk02 services-disk03 services-disk04 services-disk05 services-disk06 services-disk07 services-disk08 services-disk09 services-disk10 services-disk11 services-disk12 services-disk17]
```

we will spawn a [migration checklist](https://github.com/sul-dlss/preservation_catalog/blob/master/.github/ISSUE_TEMPLATE/storage-migration-checklist.md) ticket for each storage root, which i'll link to this issue.

blocked by successful completion of dry run outlined in #1462.

**Comment by ndushay** [comment]
## Week Before Cutover

Run all validation checks on Moabs and generate reports, for each storage root being migrated;   details in the linked individual migration checklist issue for each root.  Different roots can be run in parallel, but the reports for each root must be run in sequence.

* [services-disk02](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C (run all objects, get report of all errors, not druids ...)
    - [ ] C2M ditto
    - [ ] CV ditto
* [services-disk03](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C
    - [ ] C2M ditto
    - [ ] CV ditto
* [services-disk04](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C
    - [ ] C2M ditto
    - [ ] CV ditto
* [services-disk05](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C
    - [ ] C2M ditto
    - [ ] CV ditto
* [services-disk06](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C
    - [ ] C2M ditto
    - [ ] CV ditto
* [services-disk07](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C
    - [ ] C2M ditto
    - [ ] CV ditto
* [services-disk08](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C
    - [ ] C2M ditto
    - [ ] CV ditto
* [services-disk09](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C
    - [ ] C2M ditto
    - [ ] CV ditto
* [services-disk10](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C
    - [ ] C2M ditto
    - [ ] CV ditto
* [services-disk11](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C
    - [ ] C2M ditto
    - [ ] CV ditto
* [services-disk12](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C
    - [ ] C2M ditto
    - [ ] CV ditto
* [services-disk17](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C
    - [ ] C2M ditto
    - [ ] CV ditto

**Comment by ndushay** [comment]
## Cutover Weekend, Before HandOff to Ops

#### Final Pre-Cut-Over Reports

* [services-disk02](https://github.com/sul-dlss/preservation_catalog/issues/1478)
  - [ ] generate final pre-cutover report for objects with error status ```RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[stor_root_name,b4_cutover]```
  - [ ] get list of druids on storage root ```RAILS_ENV=production bundle exec rake prescat:reports:msr_druids[storage_root_name,druids_b4]```
* [services-disk03](https://github.com/sul-dlss/preservation_catalog/issues/1477)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk04](https://github.com/sul-dlss/preservation_catalog/issues/1476)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk05](https://github.com/sul-dlss/preservation_catalog/issues/1475)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk06](https://github.com/sul-dlss/preservation_catalog/issues/1474)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk07](https://github.com/sul-dlss/preservation_catalog/issues/1473)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk08](https://github.com/sul-dlss/preservation_catalog/issues/1472)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk09](https://github.com/sul-dlss/preservation_catalog/issues/1471)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk10](https://github.com/sul-dlss/preservation_catalog/issues/1470)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk11](https://github.com/sul-dlss/preservation_catalog/issues/1469)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk12](https://github.com/sul-dlss/preservation_catalog/issues/1467)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk17](https://github.com/sul-dlss/preservation_catalog/issues/1466)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root

#### Tell PresCat About New Storage Root

- [x] update shared_configs for prescat with the new storage root information

  - [x] create a shared_configs PR (***to base branch `preservation-catalog-migrate`***) that adjusts storage root information.

    `storage_root_map.default` in `config/settings/production.yml` should have the target storage location on the new brick named and added, and the old storage root entry removed

      ```yml
      storage_root_map:
        default:
          # services-disk02: '/services-disk02' # lines to be removed, left here for illustrative purposes
          # services-disk03: '/services-disk03'
          services-disk04: '/services-disk04'
          <snip>
          services-disk22: '/services-disk22'
      ```
  - [x] have someone merge shared_configs PR (if possible, see note at top)

- [x] use capistrano to make prescat aware of new shared_configs

    ```sh
    bundle exec cap migrate shared_configs:update
    bundle exec cap migrate passenger:restart
    ```

- [x] if you added a new storage root (the first time migrating data to a particular new storage brick), you will need to add the root to the prescat db (run this from your laptop):

    ```sh
    bundle exec cap migrate db_seed
    ```

    (yes, it's `db_seed` via capistrano)

**Comment by ndushay** [comment]
#### Final Pre-Cut-Over Reports

* [services-disk02](https://github.com/sul-dlss/preservation_catalog/issues/1478)
  - [ ] generate final pre-cutover report for objects with error status ```RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[stor_root_name,b4_cutover]```
  - [ ] get list of druids on storage root ```RAILS_ENV=production bundle exec rake prescat:reports:msr_druids[storage_root_name,druids_b4]```
* [services-disk03](https://github.com/sul-dlss/preservation_catalog/issues/1477)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk04](https://github.com/sul-dlss/preservation_catalog/issues/1476)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk05](https://github.com/sul-dlss/preservation_catalog/issues/1475)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk06](https://github.com/sul-dlss/preservation_catalog/issues/1474)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk07](https://github.com/sul-dlss/preservation_catalog/issues/1473)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk08](https://github.com/sul-dlss/preservation_catalog/issues/1472)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk09](https://github.com/sul-dlss/preservation_catalog/issues/1471)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk10](https://github.com/sul-dlss/preservation_catalog/issues/1470)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk11](https://github.com/sul-dlss/preservation_catalog/issues/1469)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk12](https://github.com/sul-dlss/preservation_catalog/issues/1467)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root
* [services-disk17](https://github.com/sul-dlss/preservation_catalog/issues/1466)
  - [ ] generate final pre-cutover report for objects with error status 
  - [ ] get list of druids on storage root

#### Tell PresCat About New Storage Root

- [ ] update shared_configs for prescat with the new storage root information

  - [ ] create a shared_configs PR (***to base branch `preservation-catalog-migrate`***) that adjusts storage root information.

    `storage_root_map.default` in `config/settings/production.yml` should have the target storage location on the new brick named and added, and the old storage root entry removed

      ```yml
      storage_root_map:
        default:
          # services-disk02: '/services-disk02' # lines to be removed, left here for illustrative purposes
          # services-disk03: '/services-disk03'
          services-disk04: '/services-disk04'
          <snip>
          services-disk22: '/services-disk22'
      ```
  - [ ] have someone else merge shared_configs PR (if possible, or merge yourself)

- [ ] use capistrano to make prescat aware of new shared_configs

    ```sh
    bundle exec cap migrate shared_configs:update
    bundle exec cap migrate passenger:restart
    ```

- [ ] if you added a new storage root (the first time migrating data to a particular new storage brick), you will need to add the root to the prescat db (run this from your laptop):

    ```sh
    bundle exec cap migrate db_seed
    ```

    (yes, it's `db_seed` via capistrano)

**Comment by ndushay** [comment]
## Cutover Weekend - Adding New Disk

#### Final Pre-Cut-Over Reports

**Comment by ndushay** [comment]
### Ops Runs with the Baton

Ops will now perform such tasks as the following:

- final migration of data from old storage root to new
- migrated content moved to final location on new brick (see #1376 )
- apply puppet PR to add new brick to preservation robots and prescat as needed
- unmount the old storage root's NFS volume so that pres cat no longer has access to the contents, leaving empty sdr2objects and deposit directories in the path that previously mounted the storage root contents. (this will make the contents of the old storage invisible to pres cat without deleting the files where they actually reside)
- more ops-y things
- notify us the data is now available in its new home.

**Comment by ndushay** [comment]
## Back to Devs After Ops Says Data Available

Confirm that the old storage root's NFS volume has been unmounted

The migrated moabs should no longer be visible in the old location (e.g., if migrating off of services-disk02, /services-disk02/sdr2objects should be present, but empty -- its moabs should only be available from the migration's target storage location). This will prevent pres cat from seeing the same moab in two places, which is currently unsupported.

- [ ] update shared_configs for prescat commenting out the old storage roots

  - [ ] create a shared_configs PR (***to base branch `preservation-catalog-migrate`***) that adjusts storage root information.

    `storage_root_map.default` in `config/settings/production.yml` should have the target storage location on the new brick named and added

      ```yml
      storage_root_map:
        default:
          # services-disk02: '/services-disk02' # migrated to pres-01
          # services-disk03: '/services-disk03' # migrated to pres-01
          # services-disk04: '/services-disk04' # migrated to pres-01
          <snip>
          services-disk22: '/services-disk22'
          pres-01: '/pres-01'
      ```
  - [ ] have someone else merge shared_configs PR (if possible, or merge yourself)

- [ ] use capistrano to make prescat aware of new shared_configs

    ```sh
    bundle exec cap migrate shared_configs:update
    bundle exec cap migrate passenger:restart
    ```

**Comment by ndushay** [comment]
## Reports After Migration

- [ ] confirm that CV workers for newly migrated objects are running via the resque GUI: https://preservation-catalog-prod-01.stanford.edu/resque/overview

Run CV, then generate reports.  In theory, different roots can be run in parallel but we will probably overwhelm the workers, so keep an eye out for resque failed jobs and the like

* [services-disk02](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run ```RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[stor_root_name,cv_after]```
* [services-disk03](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
* [services-disk04](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
* [services-disk05](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
* [services-disk06](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
* [services-disk07](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
* [services-disk08](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
* [services-disk09](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
* [services-disk10](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
* [services-disk11](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
* [services-disk12](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
* [services-disk17](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run

**Comment by ndushay** [comment]
## M2C Reports After Migration

M2C reports should be run **after** CV reports.
Run CV, then generate reports.  In theory, different roots can be run in parallel but we will probably overwhelm the workers, so keep an eye out for resque failed jobs and the like

* [services-disk02](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] M2C run completed
    - [ ] M2C error report run ```RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[stor_root_name,cv_after]```
    - [ ] CV errors manually reviewed - no new errors
* [services-disk03](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
    - [ ] CV errors manually reviewed - no new errors
* [services-disk04](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
    - [ ] CV errors manually reviewed - no new errors
* [services-disk05](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
    - [ ] CV errors manually reviewed - no new errors
* [services-disk06](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
    - [ ] CV errors manually reviewed - no new errors
* [services-disk07](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
    - [ ] CV errors manually reviewed - no new errors
* [services-disk08](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
    - [ ] CV errors manually reviewed - no new errors
* [services-disk09](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
    - [ ] CV errors manually reviewed - no new errors
* [services-disk10](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
    - [ ] CV errors manually reviewed - no new errors
* [services-disk11](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
    - [ ] CV errors manually reviewed - no new errors
* [services-disk12](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
    - [ ] CV errors manually reviewed - no new errors
* [services-disk17](https://github.com/sul-dlss/preservation_catalog/issues)
    - [ ] CV run completed
    - [ ] CV error report run
    - [ ] CV errors manually reviewed - no new errors

**Comment by ndushay** [comment]
## After Migration Success - Update PresCat, PreservationRobots and TechMdService

### Restore Preservation Catalog Archival Workers, ReST API and weekend crons

- [ ] create a shared_configs PR (***to base branch `preservation-catalog-prod`***) that reverts the worker changes made above, and keeps the new storage root config.

    `config/resque-pool.yml` should look like this:
    ```yml
    c2m: 6
    checksum_validation: 6
    ibm_us_south_delivery: 6
    m2c: 6
    moab_replication_audit: 3
    part_audit_aws_s3_east_1: 3
    part_audit_aws_s3_west_2: 3
    part_audit_ibm_us_south: 3
    results_recorder: 6
    s3_us_east_1_delivery: 6
    s3_us_west_2_delivery: 6
    zip_endpoint_events: 6
    zipmaker: 6
    zips_made: 6
    ```

- [ ] have someone else merge shared_configs PR (if possible, or merge yourself)

- [ ] deploy `master` branch of preservation_catalog to prod

    ```sh
    bundle exec cap prod deploy
    ```

- [ ] confirm there are archival workers running via the resque GUI: https://preservation-catalog-prod-01.stanford.edu/resque/overview
- [ ] confirm the ReST routes are available (e.g. go to https://preservation-catalog-prod-01.stanford.edu/v1/objects/wr934ny6689)
- [ ] confirm there are weekend cron jobs, especially CV

      Note that cron jobs are deployed on preservation-catalog-prod-02.

      ```sh
      bundle exec cap -z preservation-catalog-prod-02.stanford.edu prod ssh
      crontab -l
      ```

      there should be a line with `validate_expired_checksums!` in it.

- [ ] (Ops) turn on nagios alerts for preservation_catalog prod boxes

### Restore Preservation Robots Workers

- update shared_configs for preservation robots with the new storage root information

  - [ ] create a shared_configs PR (***to base branch `preservation_robots_prod`***) that adjusts storage root information.

    `moab.storage_roots` in `config/environments/prod.yml`  should have the target storage location on the new brick added, and the old storage root entry removed

      ```yml
      moab:
        storage_roots:
          # - '/services-disk02' # lines to be removed, left here for illustrative purposes
          # - '/services-disk03'
          - '/services-disk04'
          <snip>
          - '/services-disk23'
          - '/pres-01'
      ```
  - [ ] have someone else merge shared_configs PR (if possible, or merge yourself)

- [ ] deploy `master` branch of preservation_robots to use the new shared_configs and to turn the workers back on

    ```sh
    bundle exec cap prod deploy
    ```

  - [ ] confirm your capistrano logs show the shared_configs being updated

  - [ ] confirm there are preservation robots workers available via the resque GUI:  https://robot-console-prod.stanford.edu/workers

- [ ] (Ops) turn on nagios alerts for preservation_robots prod boxes

### Update shared_configs for technical-metadata-service

- [ ] update shared_configs for technical-metadata-service with the new storage root information

- [ ] create a shared_configs PR (***to base branch `dor-techmd-prod`***) that adjusts storage root information.

    `storage_root_map.default` in `config/settings/production.yml` should have the target storage location on the new brick named and added, and the old storage root entry removed

      ```yml
      storage_root_map:
        default:
          # services-disk02: '/services-disk02' # lines to be removed, left here for illustrative purposes
          # services-disk03: '/services-disk03'
          services-disk04: '/services-disk04'
          <snip>
          services-disk23: '/services-disk23'
          pres-01: '/pres-01'
      ```

  - [ ] deploy `master` branch of technical-metadata-service to use the new shared_configs

    ```sh
    bundle exec cap prod deploy
    ```

  - [ ] confirm your capistrano logs show the shared_configs being updated

**Comment by ndushay** [comment]
## After Cutover Weekend

- [ ] when M2C is done, generate an error report and compare it with the `m2c_b4` error reports for the migrated roots.

- [ ] confirm migrated objects can be updated 

- [ ] confirm new objects are flowing through preservation_robots steps and are being added to preservation_catalog

- [ ] watch for Honeybadger errors from preservation_robots and from preservation_catalog

- [ ] watch for preservationAuditWF errors (via Argo)

**Comment by jmartin-sul** [comment]
Once this migration has been completed successfully, we can unblock #1463, and work on getting @andrewjbtw's sign off for decommissioning the NetApp 6220 for preservation usage.

**Comment by jmartin-sul** [comment]
a couple of notable deviations from the expected script:
* there was a bunch of replication work, some for very large moabs, in the queue on friday evening.  to pause this, we:
  * edited resque-pool.yml to shut allocate 0 workers for audit jobs, and zipmaker, but left workers for the rest of the replication pipeline allocated.  because resque pool hotswap will gracefully stop workers that are occupied (i.e. will wait for them to finish their current work), the zips that were being made were able to finish, no new zips were picked up for making, and all the zips that were made were successfully delivered to their cloud endpoints.
  * after the replication pipeline settled, and no more work was in progress, we turned all worker counts to 0, as initially planned, and left the 172 remaining zipmaker jobs in queue, to be picked up when we turn the system back on in regular prod configuration.
    * i think this means we can clear the contents of `/sdr-transfers`, since all the zips there have been delivered?  but per instructions above in this ticket, the zip temp cleanup cron jobs are currently disabled.
* C2M and M2C finished much faster than expected (around 11 pm saturday), so we went ahead and started CV running.

will proceed as planned other than that.

**Comment by jmartin-sul** [comment]
just had a brief conversation w/ @ndushay over slack and call, and she/we came up w/ some questions...

### TODOs and open questions for monday morning meeting, some covered in checklist above, some not:
- [ ] do we want new content to flow to the new `pres-01` storage root?  i think we went back and forth on this in discussions the last few weeks, and neither naomi nor i remember the decision for sure.  if we want newly accessioned content to keep going to `services-disk23`, we should keep that last in the list of storage roots (_**for both pres cat and pres robots**_).
- [ ] should we re-enable a minimum of services for andrew to test accessioning?
  - to test accessioning, we'd definitely have to re-enable preservation robots as described in comment above (with storage root config consideration in prior bullet point of this comment).
  - we'd also need to re-enable all pres cat REST routes, per above checklist.
  - Q: should we leave pres cat archival workers off?
  - Q: what about pres cat cron jobs (audit queuing, zip temp cleanup)?
- [ ] should we switch techMD to using the new storage root?  i suspect yes, but we're not sure.
  - [ ] were stub/empty dirs left in place of the old storage root paths on pres robots and techMD boxes?  hopefully yes, but if not, we should make that change there too.

**Comment by justinlittman** [comment]
Switching techMD is not critical, as pres storage roots are only used when reprocessing items. Currently that is a manual process and there are no immediate plans for invoking.

**Comment by jmartin-sul** [comment]
> Switching techMD is not critical, as pres storage roots are only used when reprocessing items. Currently that is a manual process and there are no immediate plans for invoking.

good to know, thanks!  we were unsure about this.

**Comment by jmartin-sul** [comment]
helpful test druids on prod:  https://argo.stanford.edu/catalog?utf8=%E2%9C%93&q=test+object

as of this comment, the druids returned by that search are:  `%w[bh417rh6209 bp681kc5876 ff139pd0160 fm682yf0428 gc906tc2003 gw566xt7009 kp958by8405 nt592gh9590 ph871zg7756 qy367jg7757 yd443kg7630]` (as a ruby string array for easy copypasta)

```ruby
[22] pry(main)> CompleteMoab.by_druid(%w[bh417rh6209 bp681kc5876 ff139pd0160 fm682yf0428 gc906tc2003 gw566xt7009 kp958by8405 nt592gh9590 ph871zg7756 qy367jg7757 yd443kg7630]).joins(:moab_storage_root).pluck(:druid, :storage_location)
=> [["bh417rh6209", "/pres-01/sdr2objects"],
 ["ff139pd0160", "/pres-01/sdr2objects"],
 ["gc906tc2003", "/pres-01/sdr2objects"],
 ["kp958by8405", "/services-disk16/sdr2objects"],
 ["nt592gh9590", "/pres-01/sdr2objects"],
 ["ph871zg7756", "/pres-01/sdr2objects"]]
```

at present, all live on the newly added storage root, except for `kp958by8405`

note that only 6 of the 11 druids are in preservation at all.  i'm not sure if this should be surprising.

**Comment by jmartin-sul** [comment]
i'm going to go ahead and close this.  i'll create a similar (fresh) uber ticket from a cleaned up version of the instructions here (and the errata comment from monday, and some notes from naomi).

this migration is done, and #1518 captures follow up for CV results on migrated moabs in a few weeks.
