### ISSUE TITLE
ZippedMoabVersion should switch to referring to PreservedObject, rather than CompleteMoab

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1530]
#### background

Currently, `zipped_moab_versions` (`ZippedMoabVersion`) has a pointer to `complete_moabs`, with a non-null foreign key constraint.  As pointed out [here](https://github.com/sul-dlss/preservation_catalog/issues/1159#issuecomment-571377163), this makes it impossible to delete a `CompleteMoab` for which ZMVs have been created (i.e., any moab we've shipped off to cloud archives).

Per a later comment on that issue, the purpose of the existing field is to indicate from which moab an archival zip was created.  It was a tossup at the time we initially wrote that between pointing `zipped_moab_versions` to `complete_moabs` or `preserved_objects`.  Since pointing to `complete_moabs` provided just a bit of extra info, while still making it easy enough to associate the zip to the druid, we went with `complete_moabs`.  But to easily allow for more regular deletion of old moabs that have been migrated/copied to new storage, while keeping the schema sane and tightly constrained, we're going to switch to pointing to `preserved_objects` (there will _always_ be a `PreservedObject` for a druid:  an abstract parent record for all the physical instantiations is the point of `preserved_objects`).

#### TODO
- [ ] write the rails DB migration
  - [ ] add a `zipped_moab_versions.preserved_object_id` column to the schema.  it should have a foreign key constraint to `preserved_objects.id`.
  - [ ] populate the column with the appropriate values.  in sql, this is something like `UPDATE zipped_moab_versions zmv SET zmv.preserved_object_id = (SELECT preserved_object_id FROM complete_moabs cm WHERE cm.id = zmv.complete_moab_id)`.  i'm not sure off-hand if there's a more ActiveRecord-y way of doing that that still does it in one shot.  i'm also not sure if doing it in one shot will be performant enough.  if we do it by paging and updating in batches, i'd strongly favor using functionality from the `postgresql_cursor` gem (already in use in the project) so that we can keep it transactional.
  - [ ] add a non-null constraint to the new `zipped_moab_versions.preserved_object_id` column.
  - [ ] drop the old `zipped_moab_versions.complete_moab_id` col.
  - [ ] move the `last_archive_audit` column from `complete_moabs` to `preserved_objects`.
- [ ] update all app and test code that uses `ZippedMoabVersion.complete_moab[_id]` to instead use `ZippedMoabVersion.preserved_object[_id]`
  - [ ] e.g. `CompleteMoab#create_zipped_moab_versions!` and `CompleteMoab.archive_check_expired` very likely move to `PreservedObject`
  - [ ] but `ZipEndpoint.which_need_archive_copy` and `.which_have_archive_copy` seem good as-is?
  - [ ] `PartReplicationAuditJob` should switch to taking a `PreservedObject` instead of a `CompleteMoab`
    - [ ] this indicates that `AuditResults` should allow either a `MoabStorageRoot` or a `ZipEndpoint`, because there will be no clear `MoabStorageRoot` to which a part is associated once this ticket is done.  `PartReplicationAudit` should then... give the list of endpoints it's about to check?  the individual results that get added to the `results` list already include specific endpoint names as needed.
- [ ] deploy to stage
  - [ ] get a snapshot of the database (for the unlikely event that the deployment/migration goes bad)
  - [ ] drain and shut down the archiving pipeline right before this change gets deployed, to avoid possible deadlock situations or unmigrated ZMV records getting added while this migration is running.
  - [ ] deploy the change
  - [ ] turn the archiving pipeline back on
  - [ ] test versioning an existing SDR object, as well as adding an entirely new one, and confirm that archiving to the cloud still works
- [ ] once things look good on stage, deploy to prod using the same procedure.
- [ ] update documentation
  - [ ] https://github.com/sul-dlss/preservation_catalog/wiki/Investigating-a-druid-with-replication-errors
  - [ ] https://github.com/sul-dlss/preservation_catalog/blob/master/db/README.md#view-the-zip-parts-for-a-given-druid

**Comment by justinlittman** [comment]
See move_zipped_moab_version branch for migrations.
