### ISSUE TITLE
update db/README.md (including ER diagram) for recent data model changes

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1588]
there are some recent and soon-to-be-merged data model changes that will require updates to the db/README and its schema diagram:
- [x] adding the notion of a "primary" moab (#1528, #1577)
- [x] `zipped_moab_versions` points to `preserved_objects` instead of `complete_moabs` (#1530, #1589)
- [x] `CompleteMoab` should be queried for by druid _and_ storage root (not just druid), #1535 (technically this is the app code taking better advantage of the data model, not a change to the underlying schema itself)

**Comment by jmartin-sul** [comment]
from db/README.md, how to generate the ER diagram:

> Diagram generated from lucidchart.com (File > Import Data > Entity Relationship > SQL Import > PostgreSQL; follow instructions for schema dump/import, arrange tables given on left-hand toolbar)

unfortunately, i couldn't find an easily usable open source tool for generating a proper ER diagram (with the indicators for 1:1/1:many/etc relationships, FK constraints, etc).  but stanford has a license for lucidchart, so it should be free for us to use.

if this ticket is picked up before #1589 is merged, please use that branch's schema to generate the chart.

in addition to updating the ER diagram, please give db/README.md a read through, and correct table descriptions and example queries as needed.

**Comment by jmartin-sul** [comment]
fixed by https://github.com/sul-dlss/preservation_catalog/pull/1673
