### ISSUE TITLE
storage-migration cleanup: remove delay from zipmaker job 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1636]
On the final preservation storage migration to ceph style storage, we had a bunch of problems*, and one way around them was to introduce a delay before executing the zipmaker job.

This ticket is about removing that no-longer-necessary delay.

Assuming there are no issues between newly ingested content (pres-robots) and getting said content into preservation-catalog (pres-cat workers), then we are ready for this cleanup. (e.g. after 10/10) - yep.  🎉 

### Phase 1: Reduce sleep to 0 seconds:
- [x] reduce the delay in shared_configs to 0 seconds.  See https://github.com/sul-dlss/shared_configs/blob/preservation-catalog-qa/config/settings/production.yml#L61-L63
- [ ] give it at least a few days with some content running through to make sure all is well.

### Phase 2: Remove sleep code
- [ ] from prescat code (See PR #1631 and PR #1632)
- [ ] from shared_configs (qa, stage, prod)

-------
* background for the curious

Julian and John detected the problem was that even though files were written to Ceph, they weren't immediately readable by anything -- there was a file locking problem that meant the files were invisible to ?? any VM but the original writer ?? ... and we could only get the lock to release by rebooting MDS (Meta-Data Service) on Ceph storage.

Julian ultimately found a way to configure MDS to work better for us.

**Comment by julianmorley** [comment]
This was also substantially fixed by https://github.com/sul-dlss/preservation_robots/issues/405 

A particularly enthusiastic zipmaker client might still try to read a file before Robots1 has finished flushing its write buffers, but that window of danger between Robots finishing the copy and a prescat worker trying to read it should now be less than 1 second.

**Comment by mjgiarlo** [comment]
@julianmorley 🍻

**Comment by jmartin-sul** [comment]
closing in favor of https://github.com/sul-dlss/preservation_catalog/issues/2047
