### ISSUE TITLE
switch to sidekiq

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1888]
Prereqs:  

- [ ] sul-dlss/moab-versioning#189 -- make moab-versioning thread safe
- [ ] #1860 - make ResultsRecorderJob more resilient (option 2)
- [ ] #1881 - make prescat thread safe

This will also require #1882 deployed simultaneously -- replace job locking via resque

Then look at label "affected by switch to sidekiq" to see which tickets we can close.

**Comment by jmartin-sul** [comment]
thanks for noting all the blocking relationships on this!  one suggestion on that front:  i think #1882 (replace resque based job locking) blocks this work, and not vice versa.

**Comment by ndushay** [comment]
> thanks for noting all the blocking relationships on this! one suggestion on that front: i think #1882 (replace resque based job locking) blocks this work, and not vice versa.

Fixed, thanks, john.

**Comment by justinlittman** [comment]
Steps to deploy to an environment:
1. Add sidekiq configuration files to shared_configs based on resque-pool.yml.
2. Add `redis_url: redis://preservation-catalog-stage-03.stanford.edu:6379/` to production.yml in shared_configs. The correct hostname can be found in resque.yml.
3. Update puppet `kamchanSk` branch to use Sidekiq for workers (if not already done for that environment). The number of workers should match the number of Sidekiq configuration files.
4. Rebase the pres cat `sidekiq` branch on main.
5. Notify Ops
6. Shut down GB.
7. Pull shared configs: `bundle exec cap <ENV> shared_configs:pull`
8. On main, shut down resque: `bundle exec cap <ENV> resque:pool:stop`.
9. On each worker, change puppet to `kamchanSk` as root: `puppet agent --test --environment=kamchanSk`
10. Deploy the `sidekiq` branch to the environment.
11. Check the sidekiq dashboard, e.g., https://preservation-catalog-web-stage-01.stanford.edu/queues 

Cleanup:
1. Restart GB
2. Merge puppet `kamchanKs` branch.
3. Switch each server back to production branch as root: `puppet agent --test --environment=production`
4. Delete resque.yml and resque-pool.yml from shared configs for all environments.

**Comment by jmartin-sul** [comment]
small addendum to the above deployment instructions:
* When deploying a branch that uses resque-pool in place of the `sidekiq` branch (e.g. for testing weekly dependency updates before the `sidekiq` branch is merged), make sure to log onto the worker VM and shut down the old sidekiq processes (you can call `kill <PID1 ... PID_N>` on the PID list you get back from `ps -ef | grep sidekiq`).
  * you can see them shutting down by polling manually with `ps -ef | grep sidekiq`.  should take a couple minutes to complete the shut down, and each process should have `stopping` next to it while it's shutting down, shortly after the `kill` command is run.
* When deploying the `sidekiq` branch in place of a branch that's still using resque-pool, make sure to log onto the worker VM and shut down the old resque pool processes (you can call `kill -s QUIT PID` on the PID you get back for resque-pool-master when calling `ps -ef | grep resque-pool-master`).
  * you can see them shutting down by polling manually with `ps -ef | grep resque`.  should take a minute or two to complete the shut down, and the worker processes will slowly disappear as they go offline.

For both Sidekiq and resque-pool shutdown, any work in progress for the worker processes should get finished gracefully, so if there's stuff in flight when the shut down starts, it might take a little longer for the shut down to finish than if the workers were totally idle.

**Comment by jmartin-sul** [comment]
i think this was resolved by #1984
