### ISSUE TITLE
find and resolve problems caused in preservation systems by this week's network outages

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1896]
## context

_(see also [this gigantic slack thread](https://stanfordlib.slack.com/archives/G6K8R3VBK/p1656002739728479) about the issue, and [this less gigantic one](https://stanfordlib.slack.com/archives/C09M7P91R/p1655913453544779) that preceded it, and [this one](https://stanfordlib.slack.com/archives/G6K8R3VBK/p1656345253758349) about cleanup in week following the outages, as well as [this one](https://stanfordlib.slack.com/archives/C09M7P91R/p1656479655488509) about follow on cleanup; [intermittent Ceph read issues and wrap up audits](https://stanfordlib.slack.com/archives/C09M7P91R/p1657056321998129) the week of july 5)_

This week, starting Tuesday, campus has had its available electrical power greatly reduced due to a [broken line that PG&E can't yet repair because of ongoing wildfires](https://www.sfchronicle.com/bayarea/article/Stanford-power-outage-PG-E-says-it-can-t-get-17258565.php).

This has caused intermittent outages and degradation of service for the campus network.

This has lead to problems we can't fully explain with the interaction between the Ceph backed preservation storage and the VMs that read from and write to it.

The main problems we've seen are that consumers of the Ceph storage will be unable to read some files for what seem like an indefinite period (the many hours that we watched things stall on Tuesday evening, Wednesday afternoon, and Thursday of this week).  The file read operations don't throw errors, they just hang without ever returning.  Sometimes the file content itself will be available if e.g. a file is `cat`ed, but the metadata won't be (as is needed when doing an `ls -l` or other `stat` type operation on a file or the directory that contains it).

So, e.g. we'd see things like preservation robots attempting to write to the deposit folder but hanging indefinitely as the tarpipe command blocks on... something.  But the most common issue we saw by far was hanging `validate_moab` jobs in preservation_catalog.  For example, a `validate_moab` job on a Moab of 15 MB might get stuck for 12 or more hours, seemingly doing nothing (i.e. not actually computing checksums or doing file IO to compute checksums).  Normally a job like that would take a second or two at most.  It seems that the most immediate issue is some sort of lock pres robots has on the file metadata in Ceph.  Rebooting pres robots has been the only reliable way to alleviate the issue when it crops up.  After the reboot, when things start flowing again, many of the objects that were copied to the preservation deposit space were discovered to be corrupt, necessitating removal of the incorrectly written new Moab version, and a re-running of the `preservationIngestWF` from the start for the given object (yay `validate_moab` detecting bad new Moab versions!).  See also [this wiki](https://github.com/sul-dlss/preservation_catalog/wiki/validate-moab-fails-during-the-preservationIngestWF) entry about `validate_moab` failures.

It seems the (re-)occurrences of the problem correspond with large outages to parts of the network that then cause cascading failures through the network as things like routing tables are updated.  @julianmorley can likely provide more detail and correct any inaccuracies in this description.

So, the rough sequence of events we think we've seen a few times since Tuesday evening (the first time things got wedged this way) is something like:
- a bunch of networking gear on campus loses power for a while, widespread network disruption across campus ensues, the network then recovers, and things continue to be routed across the parts that still work
- applications and services on the network, like Ceph and its preservation-land consumers, respond poorly to this, in ways we don't fully understand
- from the perspective of DLSS accessioning, the mis-behavior that follows is that `validate_moab` hangs indefinitely trying to read... some... files in... some... Moabs.  If those hanging jobs are killed, other jobs working Moab updates that didn't fall in an outage window seem to consistently succeed.  But retrying the jobs that got stuck, and failed out due to someone explicitly killing a worker process, leads to the job hanging on file reads again, maybe 2/3 of the time (rough guess from @jmartin-sul)?  So retrying the manually killed jobs that hung doesn't seem to buy us much until...
- pres robots is rebooted, and then all the file reads work again, until the next network hiccup.

We think there were networking outages that triggered this situation on at least Tuesday evening, Wednesday evening, and possibly Thursday morning or afternoon?  @julianmorley or @andrewjbtw can refresh my memory on that front.  Tues night around 10 pm was the first instance of this we identified.

## TODO

- [x]  Re-enable accessioning once things are stable again.  We've shut down accessioning for now, until power and network stability are restored.  This is to keep more preservation ingests from getting wedged, and to prevent us from having to clean up more corrupt Moab versions.  Currently we've done this by just shutting down common-accessioning robots, preservation_robots, and preservation_catalog workers (by stopping resque pool and killing hung workers at the time of stoppage).  After filing this issue, I'll turn common-accessioning and preservation_robots worker counts to zero, so that we can proceed with Monday dependency updates without inadvertently re-starting accessioning, in case things are still wedged.  We can turn the worker counts back to normal once things are fixed.
- [x] Run the following audits on all created/updated preservation objects from Tuesday afternoon of this week through the end of this week.  Will add a query to obtain these druids in a comment on this issue.
  - [x] checksum validation
  - [x] replication audit
- [x] Remediate all objects that had bad preservation versions written this week, i.e. anything that is still marked as having failed the `validate-moab` workflow step and anything where either of the aforementioned audits detects an error.
  - This will involve some manual deletion of (bad) preservation content, so we're leaving this till Monday, when everyone is a bit fresher, and maybe we can pair on the issue and test out the above linked wiki entry.

Corrections and additions welcome.  This work may spawn smaller more specific tickets in this repo or the repos for other involved projects (pres robots, common-accessioning, etc).

**Comment by jmartin-sul** [comment]
We also _suspect_ that this issue is exacerbated by our use of hardlink creation in moab-versioning to copy content from the Bagit bag for the new version in the deposit space to the new Moab version in the preservation storage space.  The problem is that because the file system is mounted over NFS, this hardlink creation is circuitously translated to a copy operation underneath, and something about that unusual hardlinking strategy confuses Ceph.  We think that switching to copy from hardlinking might resolve this and a lot of our other Ceph read problems.  I'll file a ticket about changing this behavior in the moab-versioning gem, and will link back to this ticket as related.  (Side-note: the hardlinking was an attempt to reduce re-writing content, and we assumed that it was actually just re-linking files, but we later discovered that a copy operation was what was really happening underneath, even before Ceph backed the NFS share that pres services use.  This was why we were late to realize we even needed the `validate_moab` step.  Whoops!)

**Comment by julianmorley** [comment]
Another edge-case that this revealed;
- Bad content is written to preservation storage
- Validate_moab "passes" (it successfully detects a problem and reports to Argo)
- Prescat continues to process the druid, including making and distributing cloud copies of known-bad data.

It'd be nice if any issues found by validate-moab explicitly block further processing of that version by prescat.

**Comment by jmartin-sul** [comment]
> Another edge-case that this revealed;
> 
>     * Bad content is written to preservation storage
> 
>     * Validate_moab "passes" (it successfully detects a problem and reports to Argo)
> 
>     * Prescat continues to process the druid, including making and distributing cloud copies of known-bad data.
> 
> 
> It'd be nice if any issues found by validate-moab explicitly block further processing of that version by prescat.

We've discussed this before, and we should absolutely prioritize fixing this if it is an issue, but at present I really don't think this is the case.  But also, the system is complex enough that I could be wrong, and could be mis-interpreting or mis-remembering how things work.   Do you have an example druid where this has happened?

Elaboration on why I think this isn't happening...

Just because the `validate_moab` job "succeeds" (insofar as it detects and reports an error, but doesn't crash from the perspective or Resque), doesn't mean that it hands off to replication.  If `validate_moab` reports an error to workflow service, the `validate-moab` step is marked as failed, and the workflow should not proceed.  Thus, the `update-catalog` step should not run, and replication should not be triggered, as replication is triggered when the Moab version is incremented _and_ the Moab is determined to be in an `ok` state.  Perhaps there is a bug in that code, which is why I'd really like example druids.  But the intent was certainly already to guard against the situation described here.  See this code that determines whether a Moab is eligible for replication:  https://github.com/sul-dlss/preservation_catalog/blob/0e3e6e4025b8c005ff326e17dad3f6e4e59f3b29/app/models/preserved_object.rb#L74-L76

the call chain to get to that is:
* either this hook is triggered:  https://github.com/sul-dlss/preservation_catalog/blob/0e3e6e4025b8c005ff326e17dad3f6e4e59f3b29/app/models/preserved_object.rb#L14
* or this one is:  https://github.com/sul-dlss/preservation_catalog/blob/0e3e6e4025b8c005ff326e17dad3f6e4e59f3b29/app/models/complete_moab.rb#L21
* which calls this:  https://github.com/sul-dlss/preservation_catalog/blob/0e3e6e4025b8c005ff326e17dad3f6e4e59f3b29/app/models/preserved_object.rb#L41-L52
* which only considers eligible moabs because: https://github.com/sul-dlss/preservation_catalog/blob/0e3e6e4025b8c005ff326e17dad3f6e4e59f3b29/app/models/preserved_object.rb#L69-L71

A bit of empirical evidence for my current understanding: if I spot check a couple of druids in Argo that are still (as of 2022-06-24, 11:53 am pacific) marked as failing `validate_moab`, you can see that the latest entries in the DSA event log are for `preserve_request_received`, but there are no `druid_version_replicated` events for the object:
https://argo.stanford.edu/view/druid:cq573bk5233
<img width="1318" alt="Screen Shot 2022-06-24 at 11 55 40 AM" src="https://user-images.githubusercontent.com/7741604/175647981-77e6fe8e-f587-40af-80f4-6abcfe85474f.png">

https://argo.stanford.edu/view/druid:cb112zg4898
<img width="1342" alt="Screen Shot 2022-06-24 at 11 55 59 AM" src="https://user-images.githubusercontent.com/7741604/175648026-4ea9f8b3-bfd6-41cb-8aaf-b3fce5aec4ee.png">

Contrast with this druid, which was remediated after failing `validate-moab` earlier this week, and then shepharded through; you can see follow on `cleanup-workspace` and `druid_version_replicated` (for each cloud endpoint) events, triggered by the subsequent steps in the workflow:
https://argo.stanford.edu/view/gd328fs2631
<img width="1318" alt="Screen Shot 2022-06-24 at 11 58 16 AM" src="https://user-images.githubusercontent.com/7741604/175648407-a5e152a9-6c99-4494-bb7f-ccf25127bf6e.png">


Again, it is always possible that there's a bug, or that I'm mis-remembering some corner case where this does happen.  But as the linked code demonstrates, the intent is certainly already what's being asked for here, and my recollection is that the desired behavior is what's happening, which is congruent with the big of poking into the issue that I did just now.

I know sometimes DSA replication event messages get dropped, but I haven't seen any such networking errors hit the pres cat failure queue since this outage started, and the last error honeybadger recorded for pres cat attempting to contact DSA was 7 days ago as of right now, so I don't think the lack of replication events for my two example druids above are due to dropped event log messages:  https://app.honeybadger.io/projects/54415/faults?sort=last_seen_desc&q=-is%3Aignored%E2%80%81environment%3Aprod%E2%80%81

We have certainly replicated some bad content in the past, before the check was added to [confirm that the zip files we generate are at least as large as the Moab being zipped](https://github.com/sul-dlss/preservation_catalog/issues/1633).  But I believe that is a totally separate issue, as that check was placed in `ZipmakerJob` and does not need the Moab itself to be corrupt (the issue there is that incomplete zips were being generated as a result of [Ceph read issues](https://github.com/sul-dlss/preservation_catalog/issues/1633)).  We have a query in the db/README that can find instances of that, and [i've ticketed adding a check](https://github.com/sul-dlss/preservation_catalog/issues/1641) for that situation to replication audit.

**Comment by jmartin-sul** [comment]
If either of the above threads of discussion (replication proceeding ahead even if moab content is corrupt, file read timeout in `validate_moab`) results in new work, we should ticket that work separately, i think.

**Comment by jmartin-sul** [comment]
some example druids that might be useful for spot checking, that were being processed by some hung pres robots jobs i had to manually kill yesterday:

* in progress transfer object job:  wc189cc4382
* in progress  update moab jobs: dr026cn2376 hk124bj2634 pq338gf9796 tk750kc9664 wv117kb2870 hh099qp1698 gg911kq9174 mj072dp3709 jg550zn4235

the most current remediation list would be whatever is returned by argo's failed `validate-moab` facet: https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=preservationIngestWF%3Avalidate-moab%3Aerror

**Comment by jmartin-sul** [comment]
checksum validating things that got created last week (CV for updated objects will be added shortly):
```
[1] pry(main)> audit_date_lower_bound = DateTime.parse('2022-06-21')
=> Tue, 21 Jun 2022 00:00:00 +0000
[2] pry(main)> CompleteMoab.where(created_at: audit_date_lower_bound..).count
=> 8324
[3] pry(main)> CompleteMoab.where(created_at: audit_date_lower_bound..).find_each(&:validate_checksums!)
```

**Comment by jmartin-sul** [comment]
the other possibility is of course that this is an example of the problem @julianmorley was describing above, where replication archives a moab that isn't in a good state.  that was my first suspicion/fear, but if that were the case (i.e. if the moab had always been in the same bad state), i'd have expected the sizes listed on the `CompleteMoab` and `ZipPart` records to be 0, or some small number of bytes, instead of being consistent with the sizes listed in argo, which seem reasonable for the objects (one is 71.5 MB, one is 16.1, both are google books).

either way, certainly concerning, and something to get more detail on.

**Comment by jmartin-sul** [comment]
queuing checksum validation on druids that got updated last week (all the `CompleteMoab`s got updated last week, because m2c runs weekly and touches all of them; `PreservedObject` only gets updated when there's a version bump for a child `CompleteMoab`, hence the circuitous query via `PreservedObject`, so as to avoid queuing the whole catalog for CV):

```
[1] pry(main)> audit_date_lower_bound = DateTime.parse('2022-06-21')
=> Tue, 21 Jun 2022 00:00:00 +0000
[2] pry(main)> PreservedObject.where(updated_at: audit_date_lower_bound..).count
=> 229413
[3] pry(main)> PreservedObject.where(updated_at: audit_date_lower_bound..).find_each { |po| po.complete_moabs.each(&:validate_checksums!) }
```

**Comment by andrewjbtw** [comment]
It's possible I made a mistake in my remediation and somehow the files did not get re-copied via `transfer-object` when I restarted the workflow. But even in that case I would have expected a "v0001" folder to be in the druid folder.

Both bg910hd8874 and bh868zf9366 were on my list of items that failed validation at `validate-moab`, so I think it's likely that the replicated data is actually corrupt. I deleted the "v0001" folders for everything that failed there, but don't see any sign of why it wasn't recreated when I re-ran the whole preservationIngestWF.

**Comment by jmartin-sul** [comment]
stopped the above described CV run for updated druids, because it cast too wide a net (realized after discussion with @andrewjbtw that my query would catch everything that'd gone through cloud audit in the last week, not just everything that had gone through accessioning).

after discussion w/ andrew, we decide to CV just the druids from the search results for "everything that completed accessioning in the last week" and "everything that's currently still in `preservationIngestWF`".  that is, the combo of these two argo searches:
https://argo.stanford.edu/catalog?all=true&f%5Baccessioned_latest_date%5D%5B%5D=days_7
https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=preservationIngestWF%3Acomplete-ingest%3Awaiting

attaching the druid lists i got as a result of those argo searches, and the code i used to kick off CV on them:
[prescat1896-druids-accessioned-week-of-2022-06-20.txt](https://github.com/sul-dlss/preservation_catalog/files/8996459/prescat1896-druids-accessioned-week-of-2022-06-20.txt)
[prescat1896-druids-in-preservation-ingest-week-of-2022-06-20.txt](https://github.com/sul-dlss/preservation_catalog/files/8996460/prescat1896-druids-in-preservation-ingest-week-of-2022-06-20.txt)

```
[1] pry(main)> druids_accessioned_week_of_2022_06_20 = File.readlines('/opt/app/pres/prescat1896-druids-accessioned-week-of-2022-06-20.txt').map { |druid_line| druid_line.chomp.gsub('druid:', '') } ; nil

=> nil
[2] pry(main)> druids_accessioned_week_of_2022_06_20.size
=> 14651
[3] pry(main)> druids_accessioned_week_of_2022_06_20.first
=> "bb015cf9132"
[4] pry(main)> druids_accessioned_week_of_2022_06_20.last
=> "zz966gx7448"
[5] pry(main)> druids_in_preservation_ingest_week_of_2022_06_20 = File.readlines('/opt/app/pres/prescat1896-druids-in-preservation-ingest-week-of-2022-06-20.txt').map { |druid_line| druid_line.chomp.gsub('druid:', '') } ; nil

=> nil
[6] pry(main)> druids_in_preservation_ingest_week_of_2022_06_20.size
=> 3973
[7] pry(main)> druids_in_preservation_ingest_week_of_2022_06_20.first
=> "bb162cq6040"
[8] pry(main)> druids_in_preservation_ingest_week_of_2022_06_20.last
[9] pry(main)> druids_to_cv = (druids_accessioned_week_of_2022_06_20 + druids_in_preservation_ingest_week_of_2022_06_20); nil
[9] pry(main)> druids_to_cv = (druids_accessioned_week_of_2022_06_20 + druids_in_preservation_ingest_week_of_2022_06_20); nil
=> nil
[10] pry(main)> druids_to_cv.size
=> 18624
[11] pry(main)> druids_to_cv.uniq!; nil
=> nil
[12] pry(main)> druids_to_cv.size
=> 18621
[13] pry(main)> druids_to_cv.each { |druid| CompleteMoab.by_druid(druid).each(&:validate_checksums!) }
```

CV completed, and 180 errors were detected, no jobs crashed.  all errors are on things that are still in the middle of pres ingest, so we're hopeful that we can clean up a corrupt version that's in the process of being written, re-run pres ingest, and be ok.  this is the argo search that'll turn up errors.

[prescat1896_druids_with_cv_audit_error.txt](https://github.com/sul-dlss/preservation_catalog/files/8996458/prescat1896_druids_with_cv_audit_error.txt)

**Comment by jmartin-sul** [comment]
plan moving forward, based on slack and standup discussions today
- [ ] re-enable just pres robots by deploying the commit from before pres robots was turned off via configuration
- [ ] let pres robots work off the preservation ingest queue
- [ ] if dependency updates are deployed before the above queue is worked off, manually kill the resque-pool master processes for common-accessioning, so that its workers don't add to the pres ingest queue
- [ ] if the pres ingest queue is worked off before dep updates go out for the week, do the same sort of old commit deploy for common-accessioning, to turn it back on using pre-dep update code
- [ ] once the common-accessioning works off the accession wf queues, re-enable google books
- [ ] once google books runs without a hitch for a cycle or two, give the all clear and re-open accessioning to humans

if we hit a snag at any of the above steps, we'll pause and re-evaluate.

**Comment by jmartin-sul** [comment]
just kicked off a (hopefully) last large checksum validation run, against everything that was accessioned between monday 2022-06-20, to a few minutes ago.  i got the druids by using this argo facet, and saving the result to a text file (note that i made the end date tomorrow july 7, just to make it easy to get everything up to now): https://argo.stanford.edu/catalog?all=true&f%5Baccessioned_latest_dttsi%5D%5B%5D=%5B2022-06-20T00%3A00%3A00.000Z+TO+2022-07-07T23%3A59%3A59.000Z%5D&commit=submit

attaching the search result (copied from a bulk action text area populated by the above linked search):  
[prescat1896_druids_accessioned_2022-06-20_to_2022-07-06.txt](https://github.com/sul-dlss/preservation_catalog/files/9056931/prescat1896_druids_accessioned_2022-06-20_to_2022-07-06.txt)

terminal snippet where i kicked off CV from pres-02 rails console:
```ruby
[2] pry(main)> druids_accessioned_20220620_to_20220706 = File.readlines('/opt/app/pres/prescat1896_druids_accessioned_2022-06-20_to_2022-07-06.txt').map { |druid_line| druid_line.chomp.gsub('druid:', '') } ; druids_accessioned_20220620_to_20220706.size
=> 25945
[3] pry(main)> druids_accessioned_20220620_to_20220706.first
=> "bb015cf9132"
[4] pry(main)> druids_accessioned_20220620_to_20220706.last
=> "zz966gx7448"
[5] pry(main)> druids_accessioned_20220620_to_20220706[340]
=> "bh726wg6853"
[6] pry(main)> druids_accessioned_20220620_to_20220706.each { |druid| CompleteMoab.by_druid(druid).each(&:validate_checksums!) }
```

for good measure, i went to CV the (two) druids currently in `preservationIngestWF:complete-ingest:waiting`, as was done last time we ran audits for this ticket, but it turns out those were already queued for CV by the above, which is unsurprising in retrospect:
```ruby
[8] pry(main)> %w[ch545gn8760 sv230yf2808].each { |druid| CompleteMoab.by_druid(druid).each(&:validate_checksums!) }
failed to acquire lock on lock:ChecksumValidationJob-gid://preservation-catalog/CompleteMoab/4624951, because it has not expired (1657128809 <= 1657131767)
Failed enqueuing ChecksumValidationJob to Resque(checksum_validation), a before_enqueue callback halted the enqueuing execution.
failed to acquire lock on lock:ChecksumValidationJob-gid://preservation-catalog/CompleteMoab/4438199, because it has not expired (1657128809 <= 1657131837)
Failed enqueuing ChecksumValidationJob to Resque(checksum_validation), a before_enqueue callback halted the enqueuing execution.
=> ["ch545gn8760", "sv230yf2808"]
```

early update: just over 3k of the 25945 druids queued for CV have been checked, and the number of preservation audit errors returned by [this argo facet](https://argo.stanford.edu/catalog?all=true&f%5Bwf_swp_ssim%5D%5B%5D=error&f%5Bwf_swp_ssim%5D%5B%5D=error%3ApreservationAuditWF%3Apreservation-audit) has dropped from 30 to 23.  🤞 that trend continues.

**Comment by jmartin-sul** [comment]
running replication audit on the druid list i used for checksum validation this morning, covering things accessioned between monday june 20th to this morning around 10 am:

```ruby
[15] pry(main)> druids_accessioned_20220620_to_20220706 = File.readlines('/opt/app/pres/prescat1896_druids_accessioned_2022-06-20_to_2022-07-06.txt').map { |druid_line| druid_line.chomp.gsub('druid:', '') } ; druids_accessioned_20220620_to_20220706.size
=> 25945
[16] pry(main)> druids_accessioned_20220620_to_20220706[340]
=> "bh726wg6853"
[17] pry(main)> druids_accessioned_20220620_to_20220706.each { |druid| PreservedObject.find_by!(druid: druid).audit_moab_version_replication! }
```

**Comment by jmartin-sul** [comment]
looping back and officially marking this done.  https://argo.stanford.edu/view/bg910hd8874 and https://argo.stanford.edu/view/bh868zf9366 were recovered from the cloud archives, and passed checksum validation.

https://stanfordlib.slack.com/archives/C0RK5EM9N/p1657566441498629?thread_ts=1657215508.880629&cid=C0RK5EM9N
