### ISSUE TITLE
disentangle storage roots for QA and stage environments

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1986]
## background

For expediency's sake, when we spun up this application in QA, we just had it share the same storage roots that stage was already using.  We didn't anticipate any issues arising from this.  But we were wrong, and this has turned out to be problematic!

The main problem is that if a regularly scheduled audit detects an issue with a druid, it will try to report that issue to workflow service.  Thus, the primary alerts we see are along the lines of:

```
Worker
    preservation-catalog-qa-02.stanford.edu:309796 on checksum_validation at October 01, 2022
Class
    ChecksumValidationJob (via ActiveJob) 
Arguments

    ---
    job_class: ChecksumValidationJob
    job_id: 6a62e7b0-fc86-4161-966e-df05a3264122
    provider_job_id: 
    queue_name: checksum_validation
    priority: 
    arguments:
    - _aj_globalid: gid://preservation-catalog/CompleteMoab/32681
    executions: 0
    exception_executions: {}
    locale: en
    timezone: UTC
    enqueued_at: '2022-10-01T18:32:41Z'

Exception
    Dor::WorkflowException
Error
    Failed to retrieve resource: put https://workflow-service-qa.stanford.edu//objects/druid:bc224gn9675/workflows/preservationAuditWF/moab-valid (HTTP status 500)
```

I suspect that this usually occurs when the moab-to-catalog audit runs, and then later the checksum validation audit, because:
* Moab to catalog walks the storage roots, and queues a job for each path that looks like a druid tree.
* The audit job looks to see whether the druid is in preservation catalog
* If the druid was ingested in stage, but the audit is running in QA, or vice versa, pres cat will not have known about the druid before the moab to catalog run.  And then it'll add it to the database as part of that `MoabToCatalogJob`, because in a normally separated production environment, this would look like the rare situation where the system drops a REST call from pres robots to pres cat signalling a new druid version, e.g. due to network hiccup.  But because this is an unusual and slightly worrisome situation in a normal prod env, the druid will be queued for checksum validation with a status of `unknown` on the `CompleteMoab`.
* Then `ChecksumValidationJob` will run to see whether there was any data corruption introduced in this slightly odd situation.  And whether or not any corruption was found, `ChecksumValidationJob` will try to report the result for auditing the druid to the environment's workflow service.
* But of course, because that druid doesn't exist in the workflow service database, because it's not part of the environment, WFS throws an error.
* And then you have, e.g., 4000+ errors in QA for a bunch of druids that are actually from stage.

Just to make sure i had a handle on the errors in QA, and wasn't missing any that were buried but which didn't fit this pattern, i did a quick bit of analysis on the failure queue:
```ruby
# define the dump_and_return_failure_queue_entries function per this wiki entry: https://github.com/sul-dlss/preservation_catalog/wiki/Investigating-failed-Resque-Jobs/9dee47711fedaa6c0eb075dacdf74fa1b7f53397
3.0.0 :021 > cv_failures = dump_and_return_failure_queue_entries('checksum_validation_failed', max_failures_to_dump: 5000)
 => 
[{:failed_at=>"2022/10/01 11:32:00 PDT",
... 
3.0.0 :028 > cv_failures.group_by { |elt| [elt[:exception], elt[:error][0..32]] }.transform_values { |val| val.size }
 => {["Dor::WorkflowException", "Failed to retrieve resource: put "]=>4903} 
3.0.0 :029 > 
```

So looks like all 4903 at present fit the expected pattern (so i'm dumping that failure queue in a moment).

## TODO

I can imagine a few ways to dig ourselves out of this.  I'd love to hear ideas for easier approaches, but the best I've come up with so far is:
- [x] Create a new mount on the QA box, under `/`, e.g. `/services-disk-qa`.  You may want to check with ops to see how they'd prefer to provision this storage (e.g. as an NFS mount, since pres robots for the given env will need to write to the same storage root(s) that pres cat reads from).
  - `/services-disk-qa` is mounted on all 3 QA VMs;  `/services-disk-stage` is mounted on all 3 QA VMs, as well as all 3 stage VMs.
- [x] In the new mount, create two storage roots.  So you'd wind up with e.g. `/services-disk-qa/store_1` and `/services-disk-qa/store_2`.
- [x] in each of the new storage roots, create a `deposit` directory and a `sdr2objects` directory.  so you should then have e.g. `/services-disk-qa/store-1/deposit` and `/services-disk-qa/store-1/sdr2objects`, etc.  (this directory structure is expected by moab-versioning -- `deposit` is where the incoming bag sits before it's turned into a new Moab version, and `sdr2objects` is where all the Moab directory trees live)
- [ ] Write some code that will generate a list of all the fulls paths to all the preservation objects in the given environment.  A `CompleteMoab` represents our local copy of the Moab on the storage roots.  You can get the exact druid tree for a druid by doing someting like: `DruidTools::Druid.new(cm.preserved_object.druid, cm.moab_storage_root.storage_location).path.to_s` (where `cm` is a particular `CompleteMoab` instance).  So, I think you could just stick that code in a `CompleteMoab.find_each { |cm| ... }` loop, and have it put save its output to a text file?
- [ ] Shut down the QA pres robots, pres cat workers, and technical metadata workers.
- [ ] Use the list from step 3 to write a script that moves the druid trees from their old storage root to the first of the new storage roots.  So, e.g., if druid `mc256xn6106` lives at `/services-disk-stage/store2/sdr2objects/mc/256/xn/6106/mc256xn6106`, move it to `/services-disk-qa/store_1/sdr2objects/mc/256/xn/6106/mc256xn6106`.  yes, 🤢, sorry!
- [ ] update the QA shared_configs for preservation_robots, preservation_catalog, and technical-metadata-service to list just the two newly created QA storage roots, so e.g. `/services-disk-qa/store_1` and `/services-disk-qa/store_2`.
- [ ] Clear the preservation_catalog QA DB.  For safety's sake, you may want to pair on this so that two people are watching the session at the same time, because wiping the wrong env is no fun.  See here: https://github.com/sul-dlss/preservation_catalog#reset-the-catalog-for-re-seeding
- [ ] re-populate the QA database with this command: https://github.com/sul-dlss/preservation_catalog#reset-the-catalog-for-re-seeding
- [ ] re-start pres robots, pres cat workers, and technical metadata workers in QA.
- [ ] Using either the druid list from step 3, or the refreshed QA pres cat database, go to stage and remove all of the `PreservedObject` records that actually belong to QA (this will require first deleting its child `CompleteMoab` and `ZippedMoabVersion` records).  Alternatively, you could clear and re-populate stage as you did with QA, now that the storage roots have been dis-entangled.

All new QA content will flow to the second storage root, and all of the existing QA content will be updated on the first storage root.

### Alternatively

Do the above , **_but_** omit the parts about generating environment specific druid lists and moving druid trees around.  Then just reset both stage and QA across all services, including DSA and preservation, and start fresh. 🔥  If we don't care about holding onto the test data we have in those environments, this is likely the easier approach, and also will likely lead to cleaner and more consistent data across those environments.  I vaguely recall hearing of a desire to reset stage anyway, and I think there are instructions for doing so, but I'm not sure where they live.  I think whether this path would be acceptable is a question for @andrewjbtw.

Or, we could split the difference: generate the druid paths for one environment's druids, delete them all, reset that env, configure new storage roots for it as described above, and let it start running from scratch (leaving stage essentially untouched, other than purging the former QA druids from its DB).  But I don't think that's way less work than the above full differentiation, so I suspect that we want to either wipe both envs, or keep and disentangle both.

**Comment by mjgiarlo** [comment]
I got the mounts created and now I need to move on to other work.

**Comment by aaron-collier** [comment]
Per meeting discussion, closing.

**Comment by jmartin-sul** [comment]
superseded by https://github.com/sul-dlss/argo/issues/4052 and its associated full reset of stage and QA
