### ISSUE TITLE
Checklist: Production PostgreSQL & Redis rebuild

### ISSUE THREAD

**Issue by edsu** [sul-dlss/preservation_catalog#1994]
@rsmith11 is going to be rebuilding PresCat database and Redis servers on 11/3 7-9 PT. This is a checklist of things Infrastructure team want to do to ensure that we don't interrupt active replication work:

- [x] Shut down Preservation Robots (to stop feeding the PresCat queues) (resque pool stop cap command from pres robots project)
- [x] Turn off Google Books
- [x] Stop common-accessioning workers (resque pool stop cap command from common-accessioning project)
- [x] Wait for all the PresCat queues to be empty
  - [x] If we can't wait for pres cat queues to drain, snapshot any `failed job` info used for remediation (snippet for capturing resque contents)
- [x] Shut down PresCat workers (cap resque pool stop from the pres cat project)
- [x] Stop puppet on the pres cat web boxes (else it'll start up httpd on its scheduled run when it notices that we turned off httpd)
- [X] PresCat httpd (using `service`, `ksu`ed as root on web boxes)
- [x] Shut down `preservation-catalog-prod-05.stanford.edu`
- [x] Snapshot `preservation-catalog-db-prod-01.stanford.edu` PostgreSQL DB
- [x] Shut down `preservation-catalog-db-prod-01.stanford.edu` and `preservation-catalog-db-prod-02.stanford.edu`
- [x] Import PostgreSQL db snapshot on `preservation-catalog-db-prod-a.stanford.edu.eyaml` and `preservation-catalog-db-prod-b.stanford.edu.eyaml`
- [x] Start up the new Redis server under its new hostname (`preservation-catalog-redis-prod-01.stanford.edu`)
- [x] @rsmith11 will re-run puppet on all web and worker VMs to have them pick up the database config change on the pres cat boxes, since puppet manages that connection info (user and pass for the PG instance).  This will also start puppet back up.
- [x] Update PresCat resque pool config (in shared_configs) to point at new Redis `preservation-catalog-redis-prod-01.stanford.edu`.
- [x] Start Preservation Catalog Workers
  - [x] as a quick smoke test, queue a checksum validation job for a small druid, to make sure the job gets queued, and a worker can pick it up.  That should exercise both redis and PG connections.
- [X] Start Preservation Catalog httpd, check `/status/all`
- [X] Start Preservation Robots
- [X] Start common-accessioning workers
- [X] Start Google Books
- [x] Remove `preservation-catalog-db-prod-01.stanford.edu` and `preservation-catalog-db-prod-02.stanford.edu` from Puppet
- [x] once everything is confirmed to be good, ops will decommission the old Postgres and Redis boxes.

**Comment by jmartin-sul** [comment]
i think we'll also need to update the redis hostname in the resque pool config, but otherwise this looks right afaict at a quick glance.

we may also want to stop common-accessioning workers (or whatever asks pres cat for content diff when versioning).  and couldn't hurt to stop google books.

**Comment by edsu** [comment]
@rsmith11 I forget, were you talking about rebuilding Redis in place?

**Comment by rsmith11** [comment]
Yes, the Redis server will keep it's name, `preservation-catalog-prod-05`.  The database servers will get a name change though, to `preservation-catalog-db-prod-a` and `preservation-catalog-db-prod-b`.

**Comment by jmartin-sul** [comment]
adjustment based on meeting:  to minimize the need for another outage, we'll put the renamed redis box (with redis in the hostname) in place during this prod migration.

we can do the QA and stage redis VM renames if we have time during this outage window, otherwise, we'll push that off to another day.

**Comment by jmartin-sul** [comment]
since systemctl doesn't play well with our capistrano/resque-pool setup, linking the instructions for managing resque pool from the VM itself:  https://github.com/sul-dlss/preservation_catalog/wiki/Resque-Workers-Restart

**Comment by jmartin-sul** [comment]
@andrewjbtw notes that there are some large accessioning jobs in progress right now.  i don't think we have to worry about this too much wrt pres robots, common-accessioning, or pre-assembly -- none of those systems are being disrupted, so if workers common-accessioning and pres robots are shut down gracefully, their WIP can finish and next steps can pile up in queue while the workers are off.

one specific gotcha is if there's a long running `validate_moab` job that's already started on the pres cat side, and we can't wait for it to finish.  if that's the case, we can kill the job manually, and dump the failure queue info in pres cat for safety.  and if we don't get our failure queue info back in the new redis instance, we can just re-queue that failed job, or reset the step in WFS so that it gets re-run.  so that is still recoverable, we just have to be careful to keep any data sitting in pres cat redis if we can't get its queues totally drained, as was the plan.

**Comment by jmartin-sul** [comment]
how to gracefully stop resque-pool workers:
* from the project directory (so in this case, `preservation_robots`, `common-accessioning`, or `preservation_catalog`)
  * after a `git pull` and `bundle update`: `bundle exec cap resque:pool:stop`
  * if that doesn't work, you can accomplish the same by manually doing the following on the VM itself: `kill -s QUIT <resque-pool-master PID>`.  you can get the process ID by doing `ps -ef | grep resque-pool-master` from the VM.

how to determine whether the workers actually shut down:
* you can look at the worker counts in the resque web console.  when shutting down the pres cat workers, the worker count [here](https://preservation-catalog-web-prod-01.stanford.edu/resque/overview) should end up at zero.  common-accessioning and preservation_robots both show up on the shared robots Resque instance, [here](https://robot-console-prod.stanford.edu/overview).  There are 5 worker processes for pres robots, on one pres robots VM, but there are 12 total worker processes for common-accessioning, 3 on each of 4 VMs.  You can see the specific worker counts by the host on which they're running here: https://robot-console-prod.stanford.edu/workers
  * so in the end, i think once both pres robots and common-accessioning workers have been fully stopped, we'd expect the worker process count on robot resque console to drop by 17 total.
* to be extra sure, you may want to run `ps -ef | grep resque` on each VM that runs the resque-pool processes.  Once the workers are fully shut down, you should see no processes like `00:00:30 resque-1.27.4: Waiting for queue_name` or `resque-pool-master[20221031173142]: managing [3714825, 3714827, 3714829, 3714831, 3714835, 3714841, 3714847, 3714850, 3714853, 3714860, 3714867, 3714875, 3714881, 3714888, 3714890`.

Also note:  the shut down approaches described above will allow any work in progress to finish, so if a worker process has already picked up a job, the graceful shut down will let it finish.  If there is WIP and it seems like the job won't complete in an acceptable amount of time, you can `kill -9` the specific worker process ID.  **However**, as discussed on Slack this afternoon, I don't think it should be necessary to hard kill any pres robots or common-accessioning jobs.  If they have any long running work in progress, it should complete, and queue the next step, which should sit and wait to be picked up till the common-accessioning and pres robots workers are started again.  We're only shutting down pres robots and common-accessioning to prevent them from making REST calls to pres cat.  But the workflow steps that make those REST calls (content diff for common-accessioning, `update-catalog` and `validate-moab` for pres robots) should not be long running jobs.  The only workers I'd worry about having to run `kill -9` on would be pres cat's own internal workers.  We don't want them running during the migration.  If you do `kill -9` a job, you should probably note here the druid it was working on, so we can follow up on it.
