### ISSUE TITLE
try to reduce Sidekiq/Redis connection attempt timeouts

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#2244]
# Describe the bug

Timeouts when Sidekiq tries to connect to Redis to pick up jobs and/or mark them as worked (including checking/taking/clearing locks used to prevent duplicate enqueuing of the same job for the same parameters when such a job is already in queue and yet to be worked).

## User Impact

Infra team gets honeybadger alerts about connection errors, and it's unclear at a glance whether a given alert is indicative of a sustained outage or just an isolated network blip, making it harder to triage alerts and figure out what actually needs attention in terms of production troubleshooting.

## Object(s) In This Error State

None at the moment

## Steps to Reproduce, if Known

let preservation_catalog run in some environment for a week or two

## Expected behavior

Timeouts are very rare.

# Additional context

Redis connection error HB searches where timeouts show up
https://app.honeybadger.io/search?q=Redis%3A%3ACannotConnectError
https://app.honeybadger.io/search?q=RedisClient%3A%3ACannotConnectError

DLSS sees Redis timeout errors from Sidekiq jobs across many of our applications, and anecdotally, infra team developers have noticed a spike in the last few months.  Based on a quick skim of the above HB links, pres cat might account for a plurality of the timeouts in the infra portfolio?  So this seems as good a project as any to use for investigating the issue.

@justinlittman  points to this sidekiq troubleshooting doc: https://github.com/sidekiq/sidekiq/wiki/Using-Redis

A band-aid according to that is to increase the timeout, see https://github.com/sidekiq/sidekiq/wiki/Using-Redis#life-in-the-cloud

```ruby
config.redis = { url: 'redis://...', network_timeout: 5 } # in config/initializers/sidekiq.rb
```

Perhaps this is actually sufficient, at least to start?  As the Redis docs observe (see below), not all apps have the same latency requirements, and occasionally taking a few seconds instead of a few milliseconds to pick up a job should be no big deal for us.  Sidekiq default timeout is 1 second, and the Sidekiq author says: "With users seeing odd Redis behavior, I regularly see setups with latency over 5 seconds: terrible."  But also: "You should tune your network timeouts to be a little more lenient if you are seeing occasional timeout errors, it defaults to 1 second."

I think we're still in the occasional, if too frequent category?  Maybe we could try upping the timeout to e.g. 2 or 3 seconds, and seeing whether the errors go away, and whether we avoid any other undesirable behavior like stuck jobs or jobs piling up in queue.  I wouldn't expect either, but maybe longer timeouts could lead to weird deadlock issues? 🤷  If we up the timeout, it could be worth grepping the logs for the message about a job being unable to obtain a lock, to see if we're inadvertently getting more dupe jobs piling up?  Not that it's clear to me how that'd happen.

line for failure to acquire lock message is "failed to acquire lock on #{key}, because it has not expired (#{now} <= #{key_expires_at})": https://github.com/sul-dlss/preservation_catalog/blob/f6c785ad1b45f6f1efe93ef4404f096432840530/app/jobs/concerns/unique_job.rb#L105

Also, this Redis timeout isn't a particularly terrible error: because we enabled super_fetch in our Sidekiq config, we shouldn't lose jobs from the Redis queue till the jobs are actually completely run, right?  I haven't dug into the sidkiq docs on that, @justinlittman may be able to answer that more readily since iirc he found the super_fetch feature and enabled it.

To investigate further, we can use the latency history suggestion from the linked Sidekiq doc.

Tracking for latency may first need to be enabled in Redis, at least for one sort of analysis?  Based on my read of a couple Redis docs, it may be that there are two latency analysis features.

The one mentioned in the Sidekiq wiki may be available only in redis-cli, but we don't have the redis-cli installed on the app boxes.  And Justin observes that the connection latency from the app VMs to the Redis VM is what needs to be profiled.

@mjgiarlo observed that you can get the redis-cli functionality by using the Redis gem from the Rails console on the app VM.  Indeed that mostly seemed to be the case, and on stage I was able to do:

```ruby
client = Redis.new(url: Settings.redis_url) # pres cat has redis gem installed as direct dependency, so it can do the lock setting to prevent queueing duplicate jobs
client.call('CONFIG', 'SET', 'latency-monitor-threshold', '100') # => "OK"
# CONFIG SET latency-monitor-threshold 100 will record operations that take over 100 ms
client.call('latency', 'history', 'localhost') # => []
# maybe we don't see results yet bc there's not really activity right now on sat afternoon on stage?  see if running integration tests gets us some entries bc more sidekiq work?
```

The Redis docs have some tips on latency troubleshooting, from quick check list stuff to deeper profiling.
https://redis.io/docs/management/optimization/latency/
https://redis.io/docs/management/optimization/latency-monitor/
https://redis.io/commands/latency-history/

https://stackoverflow.com/questions/27735411/understanding-latency-using-redis-cli

But to do the redis-cli latency command that the Sidekiq docs suggest, which seems to be more like a realtime ping for checking connection quality at the moment, it does seem like redis-cli needs to be installed, and like this isn't available as a command that can be run from the Ruby client?  Or at least, I couldn't figure out how.  Also, it would make sense that a ping-like analysis would need to be run from the app boxes.  see also https://github.com/redis/redis/issues/5685 (about using `redis-cli --latency-history` output -- basically, it seems to me like `redis-cli --latency-history` might be a bit different from the `latency history` command in the Redis shell, that the Ruby client can also run?)

Anyway, if none of the more in-depth analysis is warranted, and a timeout increase is sufficient, this may be an easy fix.  I think to start, the steps could be something like

# TODO
- [ ] try increasing the redis network_timeout to 2 or 3 seconds in the sidekiq config in stage (add a Settings value)
- [ ] wait a week, if no deleterious effects (stuck accessioning, integration test suite not running, great increase in duplicate attempts to queue the same job)
- [ ] try increasing the redis network_timeout by the same amount in prod (add a Settings)
- [ ] wait 3 or 4 weeks, if network timeouts between pres cat sidekiq and redis slow greatly or gone away, without any of the aforementioned bad side effects, all good?
- [ ] if issue isn't resolved, and/or bad side-effects, roll back timeout change, proceed with deeper troubleshooting

**Comment by jmartin-sul** [comment]
representative screenshots of the HB search results for this sort of error seemed like helpful, but a bit distracting in the main issue description:

<img width="1302" alt="Screen Shot 2023-06-24 at 4 45 11 PM" src="https://github.com/sul-dlss/preservation_catalog/assets/7741604/67e09c16-5b05-48f2-a3c9-1f77bafba17c">
<img width="1262" alt="Screen Shot 2023-06-24 at 4 45 29 PM" src="https://github.com/sul-dlss/preservation_catalog/assets/7741604/805aeaff-2267-4bfc-8a2e-6a0d9fed438f">

**Comment by justinlittman** [comment]
Tweaks have been made and we are not receiving errors. Closing unless the problem re-occurs.
