### ISSUE TITLE
SPRINT 8 DEMO 12-08-17

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#337]
### (SPC) Seed Preservation Catalog - Run on Prod
- [ ] deploy to and run on **_STAGE_**
    - [x] single storage root (disk 8?) with many Moab failures
        - [x] check variety of Moab fails
            - [x] ideal:  want a variety of diff failures, and/or knowledge that all failures are the same
            - [x] satisfied that our validation code is what we want it to be
    - [ ]  fix 3-5 failing moabs manually, check them manually - do we have the fix right? **OR** tweak validation to allow subdirectories in content dir ... up to Julian and Lynn
    - [x]  all storage roots except first one (old format Moabs)
        - [x] invalid Moabs identified
            - [x] with error messages
            - [x] satisfied that our validation code is what we want it to be
        - [x] performance data captured
        - [x] perf data in wiki
    - [ ] keep results for M2C run
- [ ] deploy to and run on **_PROD_**
    - [ ]  all storage roots except first one (old format Moabs)
        - [x] invalid Moabs identified, with error messages
        - [ ] performance data captured
        - [ ] perf data in wiki
    - [ ] keep results for M2C run

### Prod Problem cleanup: Workflow-Archiver-Job
- [x] workflow-archiver-job monitored (#271 - proxy)
- [x] workflow-archiver-job uses latest version of workflow-archiver gem (#272 - proxy)

### (M2C) Moab to Catalog Existence Check - Coded
- [ ] implement all known requirements
    - [ ] when catalog shows valid moab
        - [ ] versions matching (moab and catalog)
        - [ ] later version of Moab than in catalog
        - [ ] earlier version of Moab than in catalog
        - [ ] newly invalid Moabs identified
    - [ ] when catalog shows existing errors
        - [ ] Moab still invalid
        - [ ] Moab now valid
    - [ ] when catalog doesn't know about moab
- [ ] rake task to run M2C
- [ ] perf data available with feature flag

### Prod Problem cleanup: Wasapi-Downloader logs/retries
- [ ] output obscuring results (#86 - proxy)

### Honeybadger
- [x] hook it up on PC (#32)
- [x] notify on deploys (#6)
- [ ] other notifications?

### Wowza Prod upgrade
- [ ] #15 (proxy) - blocked by need to sched testing?

### (M2C) Run Against Seeded Catalog on Prod
- [ ] deploy to and run on **_STAGE_**
    - [ ] smallest storage root (11) against populated Catalog satisfied
        - [ ] performance data captured
             - [ ] satisfied with performance
        - [ ] satisfied with M2C code
        - [ ] perf data in wiki
    - [ ] run on most "typical" storage root (8) against populated Catalog until satisfied 
        - [ ] performance data captured
             - [ ] satisfied with performance
        - [ ] satisfied with M2C code
        - [ ] perf data in wiki
    - [ ]  run against all storage roots except first one (old format Moabs)
        - [ ] performance data captured
             - [ ] satisfied with performance
        - [ ] satisfied with M2C code
        - [ ] perf data in wiki
- [ ] deploy to and run on **_PROD_**
    - [ ]  run against all storage roots except first one (old format Moabs)
        - [ ] performance data captured
             - [ ] satisfied with performance
        - [ ] satisfied with M2C code
        - [ ] perf data in wiki

### (TCR) Trusted Checksum Repository
- [ ] db schema
- [ ] create logic
- [ ] read logic

### (MV) Moab Validation - Fail Thoroughly
- [ ] way to get all known validation errors for a Moab.  
   - See https://docs.google.com/drawings/d/1HOE0Tt-OmF6BYCmhC3vU8dCCJlfi-JLUmAq1w2bhJhs/edit

### ReST hookups
- [ ] (PC) (MV) Moab Validation w D2D
- [ ] (PC) create_with_validation
- [ ] (PC) check_existence
- [ ] (PC) update_version_with_validation
- [ ] (PC) create
- [ ] (PC) update_version
- [ ] (PC) confirm_version

## Documentation to Show:
- [ ]  update Steps to Prod checklist https://docs.google.com/document/d/1oi9KmIKY0t6zVE7ACiIyOB4V-vQqTExGneFdFsth3Vs
    - [ ] update Seed PC to Prod checklist https://docs.google.com/document/d/1lZNmsAqVddUkjxpNlVo-2WE2IrMuUNs0rXPR_jsdE_g
    - [ ] update M2C to Prod checklist https://docs.google.com/document/d/137htAn4gK-v26jh7CILmWz2d-2ekPwvRD8WToafb-Yo

- [ ] new benchmarking data https://github.com/sul-dlss/preservation_core_catalog/wiki/Stats

- [ ] update API/MVP diagram https://docs.google.com/drawings/d/1MYKaYwq7h2Zw4gBTnI-q0GOWfTx_rGvXS08JiQ1nCu8/edit
