### ISSUE TITLE
(SPC) run seeding on prod

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#357]
This ticket will be done when:

The prerequisities:

- [x] feature flag allowing PC to allow/forbid subdirs in moab data/content dir (#359)
- [x] shared_configs /  settings.yml in PC code have correct settings (allow subdirs ...) (#359)
- [x] Status as rails enum rather than a db table (#228 - PR #363)
- [x] don't do a lookup of PreservationPolicy for every object (#347 - PR: rework some of #351)
- [x] logging level for production environment set to INFO (#361)
- [x] enum touchups (PR #375)
- [x] tagged release (v0.1.0 ?) in github of PC code 
- [x] tagged release deployed to prod (possibly just deploying master ... not sure if you can deploy a tag)

The meat:

- [ ] run a full seeding in master.
- [ ] enter performance data into seeding stats wiki (don't need profiling -- just start and end times for each storage root, per example sql queries in wiki)
