### ISSUE TITLE
(M2C) refactor pohandler specs per #453, #385

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#455]
(this grew out of Naomi writing a few tests to ensure that seeding the catalog would report errors to dor workflows)

Now that we have the class PreservedObjectHandlerResults => AuditResults and we can test logging and reporting via *that* class, we don't need to test so many outcomes (logging, etc.) with our specific pohandler tests.  

Instead, our pohandler tests can focus on testing the pohandler.results returned from calling a public method.  See PR #453

- [x] pohandler create specs (PR #453)
- [ ] pohandler check_existence specs (PR #531)
- [ ] pohandler confirm_version specs (PR #531)
- [ ] pohandler update_version specs (PR #531)
- [ ] pohandler shared_examples specs (PR #531)

- [x] pohandler_results specs (PR #530, #535)

**Comment by ndushay** [comment]
See also #416
