### ISSUE TITLE
(PC) AuditResults - generalize it -- message prefix and instance vars needs rework (see also #528)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#539]
- [x] do we actually want the message prefix on EACH result?  Could we just use it for logging and for workflow reporting as needed?  (#545)

prefix:
- [x] class is used by more than PreservedObjectHandler:  should we pass in the calling class name?  should we derive it?  should we forget it?  (#545)
~~- [ ] should endpoint info be storage_location instead of endpoint_name?~~

attributes (coded in branch audit-results-revisions)
- [x] "incoming_version" is less meaningful when it's a C2M check ... -- change to 'actual_version' as var name and in result messages (#544)
     - [x] ensure result messages have actual_version correct for C2M (#544)

- [x]  "incoming_size" -- kill this (#544)

related to #528
