### ISSUE TITLE
SPRINT 13 DEMO

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#576]
### (C2M) Catalog to Moab Existence Check
- [ ] deploy to and run on **_PROD_**
    - [ ]  run against all storage roots except first one (old format Moabs)
        - [ ] performance data captured
             - [ ] satisfied with performance
        - [ ] satisfied with C2M code
        - [ ] perf data in wiki / google chart (#568)

### Checksum Validation
- [ ] finish coding CV
    - [ ] Generate checksum for all files in moab
    - [ ] for each maninv file, compare checksums
    - [ ] for latest sigCat file compare checksums
- [ ] run on **_STAGE_** (probably only a few roots)
       - [ ] performance data captured
             - [ ] satisfied with performance
        - [ ] satisfied with CV code
        - [ ] perf data in wiki / google chart (#568)
- [ ] deploy to and run on **_PROD_**
    - [ ]  run against all storage roots except first one (old format Moabs)
        - [ ] performance data captured
             - [ ] satisfied with performance
        - [ ] satisfied with CV code
        - [ ] perf data in wiki / google chart (#568)

### Documentation to Update / Show:
- [ ]  update Steps to Prod checklist https://docs.google.com/document/d/1oi9KmIKY0t6zVE7ACiIyOB4V-vQqTExGneFdFsth3Vs
- [ ] update API/MVP diagram https://docs.google.com/drawings/d/1MYKaYwq7h2Zw4gBTnI-q0GOWfTx_rGvXS08JiQ1nCu8/edit
