### ISSUE TITLE
SPRINT 15 (2018-03-23) DEMO

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#620]
Checksum Validation
- [x] fix bug with ERRNO  / missing file (#622)
- [x] set up second prod VM to parallelize CV checks in prod (#616, #617)
- [ ] deploy to and run on **_PROD_** (#564)
    - [ ]  run against all storage roots except first one (old format Moabs)
        - [ ] performance data captured
             - [ ] satisfied with performance
        - [ ] satisfied with CV code
        - [ ] perf data in wiki / google chart (#568)

Ingest Robots
- [ ] run on STAGE to make sure we have all the plumbing right
- [ ] implement robot to update Pres Catalog
     - [ ] implement ReST calls needed in PC
- [ ] finish porting existing robots to preservation_robots
- [ ] replace existing prod robots with new code
- [ ] deprecate old code repos

**Comment by ndushay** [comment]
CV:
- nearly ready to run on two VMs simultaneously (only shared_configs left - see #617)
- ran on PROD for storage root 2
- performance:  root 2 took 2 weeks;  need to run for single checksum only, not all checksum types present (see #642)

Ingest robots:
- needed new VMs
- existing robots:  all done or have PRs except one
- ReST calls needed for new robot -- one has a PR
