### ISSUE TITLE
SPRINT 16 (2018-04-06) DEMO

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#645]
**_Checksum Validation_**
- [ ] run simultaneously on multiple VMs
    - [x] shared_configs tweaks to accomodate (#617)
    - [ ] shared affinity rules (#635)
- [ ] only compare MD5 checksum, not all available (#642)
- [ ] deploy to and run on **multiple _PROD_ VMs** (#173)
    - [ ]  run against storage roots 3-14 (2 is done)
        - [ ] performance data captured
             - [ ] satisfied with performance
        - [x] satisfied with CV code
        - [ ] perf data in wiki / google chart (#568)
- [x] ensure manually updated ETDs, when versionMetadata.xml is removed, pass CV (#636)
- [ ] rake task for single druid needs to return non-zero when errors (#633)

**_Preservation Robots_**
- [ ] run on STAGE to make sure we have all the plumbing right
- [ ] implement robot to update Pres Catalog
     - [ ] implement ReST calls needed in PC
- [ ] finish porting existing robots to preservation_robots
- [ ] don't use dor services;  use dor-workflow-services 
- [ ] port weekly_status script to preservation_robots
- [ ] add honeybadger to preservation_robots
- [ ] add whenever to preservation_robots
- [ ] replace existing prod robots with new ones
- [ ] nagios monitoring of preservation_robots
- [ ] devops docs 
- [ ] deprecate old code repos

**_Replication_**
- [ ] ticket replication work
- [ ] start doing work
