### ISSUE TITLE
SPRINT 17 (2018-04-13) DEMO

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#662]
**_Checksum Validation_**
- [ ] run simultaneously on multiple VMs
    - [ ] shared affinity rules (#635)
- [x] only compare MD5 checksum, not all available (#642)
- [x] deploy to and run on **multiple _PROD_ VMs** (#173)
    - [x]  run against storage roots 3-14 (2,10 are done; 3,4 in progress)
        - [ ] performance data captured
             - [ ] satisfied with performance
        - [ ] perf data in wiki / google chart (#568)

-----------

Stretch Goals

**_Preservation Robots_**
- [x] run on STAGE to make sure we have all the plumbing right
- [ ] implement robot to update Pres Catalog
- [x] finish porting existing robots to preservation_robots
   - [x] complete-ingest (was ingest-cleanp) (only one remaining)
- [ ] ensure each robot runs correctly
    - [x] transfer-object
    - [x] valiate-bag
    - [x] verify-apo
    - [x] update-moab
    - [ ] update-catalog
         - [ ] implement ReST calls needed in PC
         - [ ] implement robot
         - [ ] runs correctly
    - [x] complete-ingest
         - [x] runs correctly
- [x] don't use dor services;  use dor-workflow-services 
- [ ] port weekly_status script to preservation_robots
- [x] add honeybadger to preservation_robots
- [ ] add whenever to preservation_robots
- [ ] replace existing prod robots with new ones
- [ ] nagios monitoring of preservation_robots
- [ ] devops docs 
- [ ] deprecate old code repos

** _API Documentation-**

**_Replication_**
- [ ] ticket replication work
- [ ] start doing work
