### ISSUE TITLE
Sprint 18 (2018-04-27) Demo

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#669]
**_Checksum Validation_**
- [x] status settings for CV work (#655)
- [ ] continue running simultaneously on **multiple _PROD_ VMs**
  - [x] deploy latest pres_cat code to prod boxes (#680)
  - [ ]  run against storage roots 5-14 (#564)
        - [ ] performance data captured
             - [x] satisfied with performance
        - [x] error info captured
        - [ ] perf data in wiki / google chart (#568)
- [x] decide how many prod vms we want for CV and provision them
   - [x] re-run another root (besides 10 - shortest of 2, 3, 4) on stage for more stats (#681)
   - [ ] ask Julian how many prod VMs we want. (#682)
   - [x] shared affinity rules (#635)

**_Preservation Robots_**
- [x] implement update-catalog robot to update Pres Catalog
    - [ ] shared_configs / VM tweaks needed to talk to pres_cat (sul-dlss/preservation_robots#61)
    - [x] implement robot (sul-dlss/preservation_robots#7)
         - [x] test that it does what it is supposed to (on stage) (sul-dlss/preservation_robots#63)
    - [ ] turn off CSRF on pres-catalog b/c no sessions to be hijacked (#667)
- [x] weekly stats script PR (sul-dlss/preservation_robots#24)
- [ ] write useful README (how to use, how to modify, where to get more info) (sul-dlss/preservation_robots#17)
- [x] set robots up to run in PROD
    - [x] deploy to prod
    - [x] shared_configs for prod 
    - [x] ensure robots work in prod (sul-dlss/preservation_robots#62)
    - [ ] re-deploy to prod with update-catalog robot (sul-dlss/preservation_robots#7)
- ~~[ ] restart robots-master so redis knows about new robot workflow (?)~~
- [ ] devops docs (sul-dlss/preservation_robots#2, sul-dlss/preservation_robots#3)
- [ ] replace old robots with new ones in prod
  - [ ] dor-services change so common-accessioning starts NEW robot workflow
     - [x] change code (sul-dlss/preservation_robots#40)
    - [x] release dor-services gem  (sul-dlss/preservation_robots#40)
    - [x] update common-accessioning to use new dor-services gem  (sul-dlss/preservation_robots#40)
    - [x] deploy new common-accessioning  (sul-dlss/preservation_robots#40)
- [x] deprecate old code repos (sul-dlss/archive-utils#3, sul-dlss/sdr-replication#6, sul-dlss/sdr-preservation-core#89)
- [x] add whenever to preservation_robots (sul-dlss/preservation_robots#28)
- [ ] nagios monitoring of preservation_robots ((sul-dlss/preservation_robots#30)

**_Replication_**
- [ ] design doc of replication work (#671)
- [ ] ticket replication work
- [ ] start doing work
-----------

Stretch Goals

** _API Documentation_**
