### ISSUE TITLE
Sprint 19 (2018-05-11) Demo/Goals

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#735]
Sprint Goals:

Finish Robots:
* [x] Update workflow_archiver_app (sul-dlss/preservation_robots#39)
* [x] Daily robot activity script (sul-dlss/preservation_robots#76)
* [ ] Remove objects w/ druid: prefix (#722 )
* [x] Devopsdocs (sul-dlss/preservation_robots#3)

Replication:
* [x] s3 credentials from @julianmorley  for AWS Endpoint Delivery Worker(#710)
* [ ] "What endpoints should a PC go to?" Plexer Work (#713)
* [x] Determine what is required to make TCR viable (sul-dlss/trusted_checksum_repository#23)
* [x] mount sdr-transfer volume (#738, #739)

Stretch Goal:
* [ ] Determine how we want to create the zips (#737)
* [ ] In Zip Worker stub our zip creation (somehow create it or stub it out) (#707)

**Comment by atz** [comment]
Notes to self:
- CV: still running checksumming on prod, about 5 disks left
- ingest robots: finished updating workflow_archiver_app
- show DevOpsDocs & ops conerns
- show daily script output
- replication
- Spun up new stage VMs to accommodate standardized naming convention
- mounted new SDR transfers volume
