### ISSUE TITLE
sprint 21 (2018-06-08) goals/demo

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#806]
### Replication
* [x] Finish implementing zipmaker worker (#707)
* [x] Finish plexer worker:  capture zip creation metadata (for storage in pres cat and sending to amazon)  (#787)
* [ ] (Stretch?)  Ship an actual moab to the cloud using the queue

### Checksum Validation
* [ ] error analysis -- are all errors the same type? which volumes, etc

### Maintenance
* [ ] start addressing high-priority TODOs and leftover maintenance so that we can leave this work in maintainable shape (e.g. #792, #242, #320, #688; <-- prob not an exhaustive list)

### Outside work
* [ ] wind down infrastructure maintenance work (e.g. Argo PRs)
