### ISSUE TITLE
sprint 22 (2018-06-15) goals/demo

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#861]
### Replication
- [x] prevent >10G Moabs from being replicated (#850)
- [ ] single object from stage to cloud: object runs through the queues and replicates to AWS 
    - [x] US west only
        - [x] Okcomputer bug (maybe related to #727)
        - [x] Add require ‘resque/tasks’ (#842)
        - [ ] Custom configs that need to be addressed via joe (#843)
        - [x] ZipMaker has a few bugs (#844, #845) 
        - [ ] Time the transfer
    - [x] US West and US East
- [ ] single object from prod to cloud, manually triggered 

### Robots
- [ ] set status to ok (#817)

### M2C and C2M
- [ ] run smoothly via cron (see #810 - in progress)
- [x] appropriate statuses set
- [x] appropriate notifications to workflows
- [ ] appropriate worfklows errors cleared (#827)
- [ ] which logs (#858)
- [ ] log long term backup (#857)
- [ ] research most recent versioning mismatches (#863, Ben?)

```
 ["/services-disk07/sdr2objects", "unexpected_version_on_storage", 64],
 ["/services-disk10/sdr2objects", "unexpected_version_on_storage", 1],
 ["/services-disk11/sdr2objects", "unexpected_version_on_storage", 1],
 ["/services-disk12/sdr2objects", "unexpected_version_on_storage", 4],
 ["/services-disk13/sdr2objects", "unexpected_version_on_storage", 2],
 ["/services-disk14/sdr2objects", "unexpected_version_on_storage", 3],
```

### CV
- [x] error analysis -- are all errors the same type? which volumes, etc (#848)
- [x] research disk 12 invalid_checksum errors (see #848)
- [x] appropriate workflows errors cleared (#827)

**Comment by ndushay** [comment]
Sprint 23 goals is #909
