### ISSUE TITLE
Sprint 23 (2018-06-22) Goals

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#909]
“Preserve” all new updates/new objects
#### Newly created Moabs/versions
- [ ] Fix robots ok status bug (#817) 
- [x] M2C, C2M run smoothly via cron (see #810)
- [ ]  confirm appropriate worfklows errors cleared by M2C, C2M (#912)
- [ ] should M2C, C2M, CV write to their own logs? (#858)
- [x] fix log rotation/long term backup for M2C, C2M, CV ... (#857)
##### Replication
- [ ] replicate single object from prod to cloud, manually triggered (#910)
- [ ] can't determine what needs to be replicated (#899)
- [ ] robot Replication trigger hookup (#913, #812) 
- [x] PC reflects replicated status (#902)
- [ ] deal with >10G Moabs (#850-ish)

### C2A
- [ ] for each archival pres_copy, does it actually exist with correct MD5? (#813)
- [ ] for each online pres_copy, does it have all the archival pres_copies it should? (#920)

### Replicate backlog of druid versions
- [ ] can't determine what needs to be replicated (#907)
- [ ] Replication trigger hookup, etc (#812)

### Other
- [x] deploy pres_cat to prod to get work from Sprint 22 (v.0.7.3, v0.7.4)
