### ISSUE TITLE
Sprint 24 (2018-07-06) Goals

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#939]

**Comment by SaravShah** [comment]
“Preserve” all new updates/new objects
## Sprint 23 (2018-06-22) Goals

### Preserve all new versions/objects
#### Newly created Moabs/versions
- [ ] Fix robots ok status bug (#817) 
- [ ]  confirm appropriate worfklows errors cleared by M2C, C2M (#912)
- [ ] should M2C, C2M, CV write to their own logs? (#858)
##### Replication
- [ ] replicate single object from prod to cloud, manually triggered (#910)
- [ ] can't determine what needs to be replicated (#899)
- [ ] robot Replication trigger hookup (#913, #812) 
- [ ] deal with >10G Moabs (#850-ish)

### C2A
- [ ] for each archival pres_copy, does it actually exist with correct MD5? (#813)
- [ ] for each online pres_copy, does it have all the archival pres_copies it should? (#920)

### Replicate backlog of druid versions
- [ ] can't determine what needs to be replicated (#907)
- [ ] Replication trigger hookup, etc (#812)
