### ISSUE TITLE
Sprint 27 (2018-07-20)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#987]
### Finish database refactor for archival pres copies 
- [ ] rename models

### Run a bunch of replication through queues / prod 
- [x] test with manual triggering of queues for individual druids (stage) (#910)
- [x] test with manual triggering of queues for individual druids (prod) (#910)
- [ ] test with list of druids 
    - [ ] monitor performance (queue depth, processing speed, disk i/o issues, etc?)
        - [ ] number of workers should be?
- [x] test with large object

### Hook up replication trigger
- [ ] wire up automatic replication (#913, #812, #886)

### Robots ok status bug
- [x] pohandler (#817) 
- [x] controller takes param
- [x] robots use param

#### C2A
- [ ] for each online pres_copy, does it have all the archival pres_copies it should? (#920)

#### Replicate backlog of druid versions
- [ ] can't determine what needs to be replicated (#907)
- [ ] Replication trigger hookup, etc (#812)
